In [69]:
import pandas as pd
import numpy as np
import re

## Extract the Columns from the containers which needed

| Field      | Regex                           |
|               |                                    |
| Bike Name  | `^(.*?),\s*\d{4}`               |
| Model Year | `,\s*(\d{4})\s*ModelLocation:`  |
| Location   | `ModelLocation:\s*(.*?)\s*Rs\.` |
| Price      | `Rs\.\s*([\d,]+)`               |

In [70]:
import pandas as pd
import re

bike_name = []
model_year = []
location = []
price_list = [] 
finance =[]

raw_data = pd.read_csv(r"C:/Users/vinee/Innomatics- Data Analysis/Project/EDA_Data_Scraping/Bikes_data.csv")
text_data = raw_data.iloc[:, 0].astype(str)

for entry in text_data:

    # Bike Name
    name = re.search(r"^(.*?),\s*\d{4}", entry)
    bike_name.append(name.group(1).strip() if name else None)

    # Model Year
    year = re.search(r",\s*(\d{4})", entry)
    model_year.append(year.group(1) if year else None)

    # Location
    loc = re.search(r"ModelLocation:\s*(.*?)\s*Rs\.", entry)
    location.append(loc.group(1).strip().rstrip(",") if loc else None)

    # Price
    price_match = re.search(r"Rs\.\s*([\d,]+)", entry)
    price_list.append(price_match.group(1).replace(",", "") if price_match else None)

    # finance
    # Check Finance Available
    if "Finance Available" in entry:
        finance.append("Yes")
    else:
        finance.append("No")
        
df = pd.DataFrame({
    "bike_name": bike_name,
    "model_year": model_year,
    "location": location,
    "price(RS)": price_list,
    "finance(YES/NO)" : finance
})

In [71]:
df

,bike_name,model_year,location,price(RS),finance(YES/NO)
0,Royal Enfield Classic 500,2016,"Chembur, Mumbai, Maharashtra",100000,Yes
1,Honda Activa 125,2022,"Marathahalli, Bangalore, Karnataka",72000,Yes
2,Bajaj Pulsar 220F,2015,"Pune, Maharashtra",40000,Yes
3,Keeway SR 125,2024,"Pimpri-Chinchwad, Pune, Maharashtra",110000,Yes
4,Bajaj Pulsar NS 160,2022,"Bangalore, Karnataka",122000,Yes
...,...,...,...,...,...
1623,TVS Jupiter 125,2022,"Nagpur, Maharashtra",70000,Yes
1624,KTM Duke 125,2020,"Pataudi, Gurgaon, Haryana",65000,Yes
1625,Yamaha SZ-R,2012,"Ambattur, Chennai, Tamil Nadu",25000,Yes
1626,Yamaha SZ-RR,2019,"Tehatta, Nadia, West Bengal",55000,Yes
1627,Honda Shine 125 Disc,2022,"Thane, Maharashtra",70000,Yes

In [72]:
df[['city', 'state']] = df['location'].str.rsplit(",", n=1, expand=True)

In [73]:
df

,bike_name,model_year,location,price(RS),finance(YES/NO),city,state
0,Royal Enfield Classic 500,2016,"Chembur, Mumbai, Maharashtra",100000,Yes,"Chembur, Mumbai",Maharashtra
1,Honda Activa 125,2022,"Marathahalli, Bangalore, Karnataka",72000,Yes,"Marathahalli, Bangalore",Karnataka
2,Bajaj Pulsar 220F,2015,"Pune, Maharashtra",40000,Yes,Pune,Maharashtra
3,Keeway SR 125,2024,"Pimpri-Chinchwad, Pune, Maharashtra",110000,Yes,"Pimpri-Chinchwad, Pune",Maharashtra
4,Bajaj Pulsar NS 160,2022,"Bangalore, Karnataka",122000,Yes,Bangalore,Karnataka
...,...,...,...,...,...,...,...
1623,TVS Jupiter 125,2022,"Nagpur, Maharashtra",70000,Yes,Nagpur,Maharashtra
1624,KTM Duke 125,2020,"Pataudi, Gurgaon, Haryana",65000,Yes,"Pataudi, Gurgaon",Haryana
1625,Yamaha SZ-R,2012,"Ambattur, Chennai, Tamil Nadu",25000,Yes,"Ambattur, Chennai",Tamil Nadu
1626,Yamaha SZ-RR,2019,"Tehatta, Nadia, West Bengal",55000,Yes,"Tehatta, Nadia",West Bengal
1627,Honda Shine 125 Disc,2022,"Thane, Maharashtra",70000,Yes,Thane,Maharashtra

In [74]:

df["city"] = (df["city"].astype(str).str.extract(r"([^,]+)$", expand=False))

df[["city", "city"]]

            city        city
0         Mumbai      Mumbai
1      Bangalore   Bangalore
2           Pune        Pune
3           Pune        Pune
4      Bangalore   Bangalore
...          ...         ...
1623      Nagpur      Nagpur
1624     Gurgaon     Gurgaon
1625     Chennai     Chennai
1626       Nadia       Nadia
1627       Thane       Thane

[1628 rows x 2 columns]

In [75]:
df

,bike_name,model_year,location,price(RS),finance(YES/NO),city,state
0,Royal Enfield Classic 500,2016,"Chembur, Mumbai, Maharashtra",100000,Yes,Mumbai,Maharashtra
1,Honda Activa 125,2022,"Marathahalli, Bangalore, Karnataka",72000,Yes,Bangalore,Karnataka
2,Bajaj Pulsar 220F,2015,"Pune, Maharashtra",40000,Yes,Pune,Maharashtra
3,Keeway SR 125,2024,"Pimpri-Chinchwad, Pune, Maharashtra",110000,Yes,Pune,Maharashtra
4,Bajaj Pulsar NS 160,2022,"Bangalore, Karnataka",122000,Yes,Bangalore,Karnataka
...,...,...,...,...,...,...,...
1623,TVS Jupiter 125,2022,"Nagpur, Maharashtra",70000,Yes,Nagpur,Maharashtra
1624,KTM Duke 125,2020,"Pataudi, Gurgaon, Haryana",65000,Yes,Gurgaon,Haryana
1625,Yamaha SZ-R,2012,"Ambattur, Chennai, Tamil Nadu",25000,Yes,Chennai,Tamil Nadu
1626,Yamaha SZ-RR,2019,"Tehatta, Nadia, West Bengal",55000,Yes,Nadia,West Bengal
1627,Honda Shine 125 Disc,2022,"Thane, Maharashtra",70000,Yes,Thane,Maharashtra

## Remove location columns

In [76]:
df.drop(columns=["location"],inplace=True)

In [77]:
df.head()

,bike_name,model_year,price(RS),finance(YES/NO),city,state
0,Royal Enfield Classic 500,2016,100000,Yes,Mumbai,Maharashtra
1,Honda Activa 125,2022,72000,Yes,Bangalore,Karnataka
2,Bajaj Pulsar 220F,2015,40000,Yes,Pune,Maharashtra
3,Keeway SR 125,2024,110000,Yes,Pune,Maharashtra
4,Bajaj Pulsar NS 160,2022,122000,Yes,Bangalore,Karnataka

## correct the type of price

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1628 entries, 0 to 1627
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   bike_name        1602 non-null   object
 1   model_year       1602 non-null   object
 2   price(RS)        1581 non-null   object
 3   finance(YES/NO)  1628 non-null   object
 4   city             1628 non-null   object
 5   state            1522 non-null   object
dtypes: object(6)
memory usage: 76.4+ KB

In [79]:
df["price(RS)"]=df["price(RS)"].astype("Int64")

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1628 entries, 0 to 1627
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   bike_name        1602 non-null   object
 1   model_year       1602 non-null   object
 2   price(RS)        1581 non-null   Int64
 3   finance(YES/NO)  1628 non-null   object
 4   city             1628 non-null   object
 5   state            1522 non-null   object
dtypes: Int64(1), object(5)
memory usage: 78.0+ KB

## Drop the duplicates values from data

In [81]:
df.drop_duplicates(inplace=True)

In [82]:
df

,bike_name,model_year,price(RS),finance(YES/NO),city,state
0,Royal Enfield Classic 500,2016,100000,Yes,Mumbai,Maharashtra
1,Honda Activa 125,2022,72000,Yes,Bangalore,Karnataka
2,Bajaj Pulsar 220F,2015,40000,Yes,Pune,Maharashtra
3,Keeway SR 125,2024,110000,Yes,Pune,Maharashtra
4,Bajaj Pulsar NS 160,2022,122000,Yes,Bangalore,Karnataka
...,...,...,...,...,...,...
1623,TVS Jupiter 125,2022,70000,Yes,Nagpur,Maharashtra
1624,KTM Duke 125,2020,65000,Yes,Gurgaon,Haryana
1625,Yamaha SZ-R,2012,25000,Yes,Chennai,Tamil Nadu
1626,Yamaha SZ-RR,2019,55000,Yes,Nadia,West Bengal
1627,Honda Shine 125 Disc,2022,70000,Yes,Thane,Maharashtra

In [83]:
df.isna().sum()

bike_name          17
model_year         17
price(RS)          42
finance(YES/NO)     0
city                0
state              94
dtype: int64

In [84]:
df.dropna(inplace= True)

In [85]:
df.isna().sum()

bike_name          0
model_year         0
price(RS)          0
finance(YES/NO)    0
city               0
state              0
dtype: int64

In [86]:
df.reset_index(drop=True,inplace=True)

In [87]:
df['city'].value_counts()

city
 Bangalore    128
Bangalore      87
 Mumbai        73
Hyderabad      65
Pune           65
             ...
Belgaum         1
Gorakhpur       1
Chittoor        1
Kannauj         1
 Purulia        1
Name: count, Length: 324, dtype: int64

In [88]:
## fix spelling mistakes and extra spacem

In [89]:
df['state'].unique()

array([' Maharashtra', ' Karnataka', ' Delhi', ' Andhra Pradesh',
       ' Uttar Pradesh', ' Telangana', ' Tamil Nadu', ' West Bengal',
       ' Rajasthan', ' Gujarat', ' Haryana', ' Punjab', ' Assam',
       ' Orissa', ' Kerala', ' Madhya Pradesh', ' Bihar', ' Goa',
       ' Utarakhand', ' Chhattisgarh', ' Dadra Nagar Haveli',
       ' Himachal Pradesh', ' Pondicherry', ' Jammu Kashmir',
       ' Jharkhand', ' Arunachal Pradesh'], dtype=object)

In [90]:
state_map = {
    "Orissa": "Odisha",
    "Utarakhand": "Uttarakhand",
    "Dadra Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "Jammu Kashmir": "Jammu and Kashmir",
    "Pondicherry": "Puducherry"
}

df["state"] = df["state"].str.strip().replace(state_map)

In [91]:
df['state'].unique()

array(['Maharashtra', 'Karnataka', 'Delhi', 'Andhra Pradesh',
       'Uttar Pradesh', 'Telangana', 'Tamil Nadu', 'West Bengal',
       'Rajasthan', 'Gujarat', 'Haryana', 'Punjab', 'Assam', 'Odisha',
       'Kerala', 'Madhya Pradesh', 'Bihar', 'Goa', 'Uttarakhand',
       'Chhattisgarh', 'Dadra and Nagar Haveli and Daman and Diu',
       'Himachal Pradesh', 'Puducherry', 'Jammu and Kashmir', 'Jharkhand',
       'Arunachal Pradesh'], dtype=object)

In [92]:
# df["company"] = df["bike_name"].str.split().str[0]
df['Company'] = df['bike_name'].str.extract(r'^(\w+)')

In [93]:
df

,bike_name,model_year,price(RS),finance(YES/NO),city,state,Company
0,Royal Enfield Classic 500,2016,100000,Yes,Mumbai,Maharashtra,Royal
1,Honda Activa 125,2022,72000,Yes,Bangalore,Karnataka,Honda
2,Bajaj Pulsar 220F,2015,40000,Yes,Pune,Maharashtra,Bajaj
3,Keeway SR 125,2024,110000,Yes,Pune,Maharashtra,Keeway
4,Bajaj Pulsar NS 160,2022,122000,Yes,Bangalore,Karnataka,Bajaj
...,...,...,...,...,...,...,...
1490,TVS Jupiter 125,2022,70000,Yes,Nagpur,Maharashtra,TVS
1491,KTM Duke 125,2020,65000,Yes,Gurgaon,Haryana,KTM
1492,Yamaha SZ-R,2012,25000,Yes,Chennai,Tamil Nadu,Yamaha
1493,Yamaha SZ-RR,2019,55000,Yes,Nadia,West Bengal,Yamaha
1494,Honda Shine 125 Disc,2022,70000,Yes,Thane,Maharashtra,Honda

In [94]:
df["Company"].unique()

array(['Royal', 'Honda', 'Bajaj', 'Keeway', 'Hero', 'Kawasaki', 'TVS',
       'Benelli', 'Yamaha', 'Jawa', 'Suzuki', 'KTM', 'Bicycle', 'Oben',
       'Triumph', 'Ultraviolette', 'Amo', 'Benling', 'Mahindra',
       'Okinawa', 'Ola', 'Ather', 'Kinetic', 'UM', 'BMW', 'River',
       'Harley', 'Vida', 'Revolt', 'Aprilia', 'Yezdi', 'Ampere', 'Vespa',
       'rilox', 'Tork', 'Brixton', 'BGauss', 'Joy', 'Husqvarna', 'Odysse',
       'BSA', 'Ducati'], dtype=object)

In [95]:
brand_map = {
    "Royal": "Royal Enfield",
    "rilox": "Rilox",
    "Odysse": "Odysse Electric",
    "Amo": "AMO Electric",
    "BGauss": "BGAUSS",
    "Joy": "Joy e    bike",
    "UM": "UM Motorcycles",
    "River": "River Electric",
    "Vida": "Vida (Hero Electric)",
    "Mahindra": "Mahindra Electric",
    "Kinetic": "Kinetic Green",
    "Revolt": "Revolt Motors"
}

df["Company"] = df["Company"].replace(brand_map)

In [96]:
df["Company"].unique()

array(['Royal Enfield', 'Honda', 'Bajaj', 'Keeway', 'Hero', 'Kawasaki',
       'TVS', 'Benelli', 'Yamaha', 'Jawa', 'Suzuki', 'KTM', 'Bicycle',
       'Oben', 'Triumph', 'Ultraviolette', 'AMO Electric', 'Benling',
       'Mahindra Electric', 'Okinawa', 'Ola', 'Ather', 'Kinetic Green',
       'UM Motorcycles', 'BMW', 'River Electric', 'Harley',
       'Vida (Hero Electric)', 'Revolt Motors', 'Aprilia', 'Yezdi',
       'Ampere', 'Vespa', 'Rilox', 'Tork', 'Brixton', 'BGAUSS',
       'Joy e    bike', 'Husqvarna', 'Odysse Electric', 'BSA', 'Ducati'],
      dtype=object)

In [97]:
df

,bike_name,model_year,price(RS),finance(YES/NO),city,state,Company
0,Royal Enfield Classic 500,2016,100000,Yes,Mumbai,Maharashtra,Royal Enfield
1,Honda Activa 125,2022,72000,Yes,Bangalore,Karnataka,Honda
2,Bajaj Pulsar 220F,2015,40000,Yes,Pune,Maharashtra,Bajaj
3,Keeway SR 125,2024,110000,Yes,Pune,Maharashtra,Keeway
4,Bajaj Pulsar NS 160,2022,122000,Yes,Bangalore,Karnataka,Bajaj
...,...,...,...,...,...,...,...
1490,TVS Jupiter 125,2022,70000,Yes,Nagpur,Maharashtra,TVS
1491,KTM Duke 125,2020,65000,Yes,Gurgaon,Haryana,KTM
1492,Yamaha SZ-R,2012,25000,Yes,Chennai,Tamil Nadu,Yamaha
1493,Yamaha SZ-RR,2019,55000,Yes,Nadia,West Bengal,Yamaha
1494,Honda Shine 125 Disc,2022,70000,Yes,Thane,Maharashtra,Honda

In [98]:
parts = df["bike_name"].str.split(" ",n=1, expand=True)

df["model_name"]= parts[1]

In [99]:
df["model_name"] = df["model_name"].str.replace(r"\bEnfield\b", "", regex=True).str.replace(r"\s+", " ", regex=True).str.strip()

In [100]:
df

,bike_name,model_year,price(RS),finance(YES/NO),city,state,Company,model_name
0,Royal Enfield Classic 500,2016,100000,Yes,Mumbai,Maharashtra,Royal Enfield,Classic 500
1,Honda Activa 125,2022,72000,Yes,Bangalore,Karnataka,Honda,Activa 125
2,Bajaj Pulsar 220F,2015,40000,Yes,Pune,Maharashtra,Bajaj,Pulsar 220F
3,Keeway SR 125,2024,110000,Yes,Pune,Maharashtra,Keeway,SR 125
4,Bajaj Pulsar NS 160,2022,122000,Yes,Bangalore,Karnataka,Bajaj,Pulsar NS 160
...,...,...,...,...,...,...,...,...
1490,TVS Jupiter 125,2022,70000,Yes,Nagpur,Maharashtra,TVS,Jupiter 125
1491,KTM Duke 125,2020,65000,Yes,Gurgaon,Haryana,KTM,Duke 125
1492,Yamaha SZ-R,2012,25000,Yes,Chennai,Tamil Nadu,Yamaha,SZ-R
1493,Yamaha SZ-RR,2019,55000,Yes,Nadia,West Bengal,Yamaha,SZ-RR
1494,Honda Shine 125 Disc,2022,70000,Yes,Thane,Maharashtra,Honda,Shine 125 Disc

## Removes nun vlues of model bike

In [101]:
li = np.arange(0,1495)
li[df["model_name"].isna()]

array([ 670,  905, 1075, 1298])

In [102]:
df.iloc[670]

bike_name               Bajaj
model_year               2017
price(RS)               82000
finance(YES/NO)           Yes
city                Bangalore
state               Karnataka
Company                 Bajaj
model_name               None
Name: 670, dtype: object

In [103]:
df.dropna(subset=["model_name"], inplace=True)

In [104]:
df["model_name"].isna().sum()

np.int64(0)

In [105]:
df

,bike_name,model_year,price(RS),finance(YES/NO),city,state,Company,model_name
0,Royal Enfield Classic 500,2016,100000,Yes,Mumbai,Maharashtra,Royal Enfield,Classic 500
1,Honda Activa 125,2022,72000,Yes,Bangalore,Karnataka,Honda,Activa 125
2,Bajaj Pulsar 220F,2015,40000,Yes,Pune,Maharashtra,Bajaj,Pulsar 220F
3,Keeway SR 125,2024,110000,Yes,Pune,Maharashtra,Keeway,SR 125
4,Bajaj Pulsar NS 160,2022,122000,Yes,Bangalore,Karnataka,Bajaj,Pulsar NS 160
...,...,...,...,...,...,...,...,...
1490,TVS Jupiter 125,2022,70000,Yes,Nagpur,Maharashtra,TVS,Jupiter 125
1491,KTM Duke 125,2020,65000,Yes,Gurgaon,Haryana,KTM,Duke 125
1492,Yamaha SZ-R,2012,25000,Yes,Chennai,Tamil Nadu,Yamaha,SZ-R
1493,Yamaha SZ-RR,2019,55000,Yes,Nadia,West Bengal,Yamaha,SZ-RR
1494,Honda Shine 125 Disc,2022,70000,Yes,Thane,Maharashtra,Honda,Shine 125 Disc

In [106]:
df.isna().sum()

bike_name          0
model_year         0
price(RS)          0
finance(YES/NO)    0
city               0
state              0
Company            0
model_name         0
dtype: int64

In [107]:
df["Company"].unique()

array(['Royal Enfield', 'Honda', 'Bajaj', 'Keeway', 'Hero', 'Kawasaki',
       'TVS', 'Benelli', 'Yamaha', 'Jawa', 'Suzuki', 'KTM', 'Bicycle',
       'Oben', 'Triumph', 'Ultraviolette', 'AMO Electric', 'Benling',
       'Mahindra Electric', 'Okinawa', 'Ola', 'Ather', 'Kinetic Green',
       'UM Motorcycles', 'BMW', 'River Electric', 'Harley',
       'Vida (Hero Electric)', 'Revolt Motors', 'Aprilia', 'Yezdi',
       'Ampere', 'Vespa', 'Rilox', 'Tork', 'Brixton', 'BGAUSS',
       'Joy e    bike', 'Husqvarna', 'Odysse Electric', 'BSA', 'Ducati'],
      dtype=object)

In [108]:
# df[(df["Company"] == 'Bicycle')].count()

In [109]:
brand_country = {
    "Royal Enfield": "UK / India",
    "Honda": "Japan",
    "Bajaj": "India",
    "Keeway": "Hungary",
    "Hero": "India",
    "Kawasaki": "Japan",
    "TVS": "India",
    "Benelli": "Italy",
    "Yamaha": "Japan",
    "Jawa": "Czech Republic",
    "Suzuki": "Japan",
    "KTM": "Austria",
    "Oben": "India",
    "Triumph": "United Kingdom",
    "Ultraviolette": "India",
    "AMO Electric": "India",
    "Benling": "China",
    "Mahindra Electric": "India",
    "Okinawa": "India",
    "Ola": "India",
    "Ather": "India",
    "Kinetic Green": "India",
    "UM Motorcycles": "USA",
    "BMW": "Germany",
    "River Electric": "India",
    "Harley": "USA",
    "Vida (Hero Electric)": "India",
    "Revolt Motors": "India",
    "Aprilia": "Italy",
    "Yezdi": "Czech Republic",
    "Ampere": "India",
    "Vespa": "Italy",
    "Rilox": "China",
    "Tork": "India",
    "Brixton": "Austria",
    "BGAUSS": "India",
    "Joy e    bike": "India",
    "Husqvarna": "Sweden",
    "Odysse Electric": "India",
    "BSA": "United Kingdom",
    "Ducati": "Italy",
    "Bicycle":"India"
}

df["brand_origin"] = df["Company"].map(brand_country)

In [110]:
df

,bike_name,model_year,price(RS),finance(YES/NO),city,state,Company,model_name,brand_origin
0,Royal Enfield Classic 500,2016,100000,Yes,Mumbai,Maharashtra,Royal Enfield,Classic 500,UK / India
1,Honda Activa 125,2022,72000,Yes,Bangalore,Karnataka,Honda,Activa 125,Japan
2,Bajaj Pulsar 220F,2015,40000,Yes,Pune,Maharashtra,Bajaj,Pulsar 220F,India
3,Keeway SR 125,2024,110000,Yes,Pune,Maharashtra,Keeway,SR 125,Hungary
4,Bajaj Pulsar NS 160,2022,122000,Yes,Bangalore,Karnataka,Bajaj,Pulsar NS 160,India
...,...,...,...,...,...,...,...,...,...
1490,TVS Jupiter 125,2022,70000,Yes,Nagpur,Maharashtra,TVS,Jupiter 125,India
1491,KTM Duke 125,2020,65000,Yes,Gurgaon,Haryana,KTM,Duke 125,Austria
1492,Yamaha SZ-R,2012,25000,Yes,Chennai,Tamil Nadu,Yamaha,SZ-R,Japan
1493,Yamaha SZ-RR,2019,55000,Yes,Nadia,West Bengal,Yamaha,SZ-RR,Japan
1494,Honda Shine 125 Disc,2022,70000,Yes,Thane,Maharashtra,Honda,Shine 125 Disc,Japan

In [111]:
new_order = [
    "brand_origin","Company","bike_name","model_name",
    "model_year","price(RS)","city","state","finance(YES/NO)"
]

df = df[new_order]

In [112]:
df.head()

,brand_origin,Company,bike_name,model_name,model_year,price(RS),city,state,finance(YES/NO)
0,UK / India,Royal Enfield,Royal Enfield Classic 500,Classic 500,2016,100000,Mumbai,Maharashtra,Yes
1,Japan,Honda,Honda Activa 125,Activa 125,2022,72000,Bangalore,Karnataka,Yes
2,India,Bajaj,Bajaj Pulsar 220F,Pulsar 220F,2015,40000,Pune,Maharashtra,Yes
3,Hungary,Keeway,Keeway SR 125,SR 125,2024,110000,Pune,Maharashtra,Yes
4,India,Bajaj,Bajaj Pulsar NS 160,Pulsar NS 160,2022,122000,Bangalore,Karnataka,Yes

In [113]:
df['model_name'].unique()

array(['Classic 500', 'Activa 125', 'Pulsar 220F', 'SR 125',
       'Pulsar NS 160', 'CB Hornet 160R ABS', 'Splendor Plus IBS i3s',
       'Versys 650 BS6 2021', '2023 Interceptor 650', 'Pulsar 150 BS6',
       'Raider Split Seat', 'Thunderbird 350', 'Imperiale 400',
       'Destini 125 Xtec', 'CB350RS', 'Activa', 'FZ25',
       '42 Bobber Black Mirror', 'FZ-S', 'Gixxer SF 250 BS6', 'V15',
       'Classic Signals Stormrider Sand', 'Jupiter', 'Duke 125 2022',
       'East coast 7speed oldskool', 'EV Rorr EZ Sigma', 'Speed 400',
       'Continental GT 650', 'Hunter 350 Metro', 'F77 SuperStreet',
       'Jaunty Pro', 'Classic 350 Redditch Red', 'Wego', 'Pulsar 135LS',
       'YZF R15 V2', 'Falcon', 'Dio Standard', 'Activa 3G', 'Dominar 250',
       'Avenger 220 DTS-i', 'Hunk', 'Hornet 2.0', 'Splendor',
       'Pulsar 180', 'Centuro', 'Pulsar AS 150', 'Pulsar 220 DTSi',
       'NTORQ 125', 'Praise Pro', 'Activa 6G Dlx', 'FZ-X',
       'Apache RR 310 BTO', 'Pulsar 180 DTSi', 'Avenger Street 160',
       'NTORQ 125 Race XP', 'Glamour BS6', 'Pulsar 150 DTSi',
       'Meteor 350 Stellar', 'FZ-S FI V2', 'S1X Plus', 'Passion Pro',
       'CB Trigger', '450X', 'R15M', 'CB Shine', 'XPulse 200T 4V',
       'Duke 200 2024', 'Rizta Z', 'CB Shine SP', 'Activa 4G',
       'Pulsar N250', 'TRK 502 BS6', 'Classic Desert Storm',
       'Pulsar NS125 BS6', 'Platina 100 ES', 'Apache RTR 160 4V BS6',
       'SP 125 BSVI', 'Chetak Electric', 'Z900 2022', 'Jupiter ZX',
       'Access 125 Ride Connect Edition', 'Pulsar N160',
       'Intruder 150 FI', 'Green Zing Electric', 'FZS 25 BS6',
       'Renegade Commando Mojave', 'Pulsar AS 200', 'G 310 R', 'Duke 200',
       'Bullet Electra', 'Jupiter Classic 110', 'CB Unicorn 160',
       'Himalayan 2021', 'S1 Pro', 'Xtreme 125R Dual Channel ABS',
       'Radeon', '450S', 'Avenger Cruise 220', 'Splendor Plus',
       'Duke 200 ABS', 'Pulsar N160 Dual Channel ABS', 'FZ-S FI Ver 4.0',
       'Passion Plus', 'R15 V4', 'CB Hornet 160R', 'Passion X Pro',
       'CB Unicorn', 'Thunderbird 500', 'FZ-S FI V3', 'Classic 350',
       'Duke 250 2025', 'Apache RR 310', 'S1', 'Activa 6G', 'Livo Disc',
       'Hornet 2.0 Repsol Edition', 'Apache RTR 160 4V', 'Intruder 150',
       'G 310 GS', 'Dominar 250 2022', 'Chetak 3503', 'S1 Air 3kWh',
       'Fascino S', 'iQube ST', '390 Adventure 2022',
       'Splendor Plus Xtec', 'Avenger Street 150', 'Shine 125 Disc',
       'Indie', 'Thunderbird X 350', 'forty two', 'Pulsar NS400Z 2025',
       'Jupiter 125', 'S1X 3 kWh', 'Aerox 155', 'Pulsar 200 NS ABS',
       'Meteor 350', '302R', 'Gixxer SF', 'Access 125', '42 FJ',
       'Dominar 400 ABS BS6', 'EV Rorr EZ', 'Pulsar NS200', 'MT-15',
       'G 310 RR', 'Avenger Street 180', 'Bullet Standard 350',
       'Davidson X440 Denim', '450S 2025', 'Pulsar RS 200 BS6', 'V1 Plus',
       'FZ1', 'Dream Yuga', 'Passion Pro BS6', 'XPulse 200',
       'Avenger 200 DTS-i', 'Pulsar RS 200 ABS', 'S1 3kWh', 'RC 200 GP',
       'Himalayan', 'GS 150R', 'V1 Pro', 'Classic 350 BS VI', 'Achiever',
       'Radeon BS6', 'Davidson X440 S', 'RV 400', 'FZ16',
       'Classic Stealth Black', 'Meteor 350 Supernova', 'Shine 125',
       'Jupiter ZX BS6', '390 Adventure 2023', 'Glamour 125 Drum',
       'Pulsar RS 200', 'YZF R15 V3', 'Livo Drum',
       'Electric Optima CX2.0', 'RS 457',
       'CB350C DLX Pro Special Edition', 'Himalayan BS VI',
       'Chetak Premium 2023 Edition', 'MT-15 Ver 2.0', 'YZF R15 S V3.0',
       '350 Legacy Edition', 'Duke 250 2020', 'CB350 DLX Pro',
       'Hunter 350 2025', 'Pulsar NS 125', 'HF Deluxe',
       'Interceptor 650 Twin', 'Speed 400 2025', 'S1 Pro Gen 3', 'SR 160',
       'Xtreme 125R', 'Apache RTR 160', 'Classic 350 Dual Channel BS6',
       'Scram 411', 'SS125', 'Hunter 350 Retro', 'Roadster Red',
       'Pulsar N250 Dual Channel ABS', 'Xtreme 125R Single Seat',
       'Gixxer SF BS6', 'S1 Pro Gen2', 'Thunderbird TwinSpark 350',
       'Glamour 125', 'forty two BS6', 'Magnus', 'RV400 BRZ',
       'Activa 6G Std', 'Renegade Commando', 'Glamour Xtec', 'Bear 650',
       'ZX 125 BS6', 'Duke 250', 'Activa 5G Limited Edition',
       'Roadster Dark', 'RX 135', 'Xtreme 160R 4V Standard',
       'Activa 125 BS6', 'Unicorn Dazzler', 'S1 Air', 'Jawa BS6',
       'Apache RTR 200 4V ABS Race Edition 2.0', 'TNT 600 i',
       'Urban Terrain Blitz Kids Cycle 16T', 'Pleasure Plus XTec',
       'Adventure Matte', 'NTORQ 125 Race Edition', 'Tiger 900 Rally',
       'Scooty Pep Plus BS6', 'Apache RTR 160 4V Special Edition',
       '250 Adventure 2022', 'RV400 Stealth Black Limited Edition',
       'Destini Prime', 'Shine BS6', '2022 Meteor 350', 'Saluto 125',
       'iQube Electric', 'Gixxer Gixxer SF 150', 'Apache RTR 310',
       'Discover 100 DTS-Si', 'Discover 100', 'Raider SX', 'Bullet 350',
       'Platina 100', 'Chetak 3501 Standard', 'Scrambler Single Tone',
       'Z650 ABS', 'Trek', 'XBlade', 'Pulsar 150 Twin Disc',
       'Glamour 125 Disc', 'Chetak Urbane', 'Bullet 350 ES BS6',
       'Discover 125', 'Gixxer SF 250', 'SXR 160', 'CD 100SS', 'Jawa',
       'Apache RTR 200 4V 2022', 'Apache RR 310 2025', 'Himalayan 450',
       'Pulsar 150', 'Pleasure Plus BS6', 'nova', 'CB125 Hornet',
       'CBZ Xtreme', '2022 CB300R', 'Hness Anniversary Edition',
       'Livo 110', 'Aviator', 'iQube S', 'Avon Charge', 'V12', 'VXL 125',
       'Splendor Plus i3s Black and Accent', 'HF Deluxe BS6',
       'Xpulse 200 4V', 'CB200X', 'Avenger Cruise 220 BS6', 'Activa 5G',
       'CBR 150R', 'Pleasure', 'Kratos R', 'Dio', 'Classic Gunmetal Grey',
       'CBF Stunner', 'Karizma XMR', 'Crossfire 500 X',
       'Adventure Matte 2024', 'S1 X Gen 3 4kWh', 'Pulsar 125 Split Seat',
       '42 Dual Channel ABS AllStar Black', 'Classic 350 Redditch Green',
       'Passion Pro i3s', 'FZ', 'SXL 125', 'S1X', 'CB300R', 'Dream Neo',
       'FZ FI V2', 'Davidson Street 750', 'Fascino', 'Avenger Street 220',
       'Classic Chrome', 'Cygnus Ray ZR', 'Davidson Street Rod',
       'MT-15 BS6', '390 Adventure X 2025', 'SZ-RR',
       'Raider Black Panther Edition', 'Unicorn', 'XPulse 200T BS6',
       'Grazia 125 BS6', 'Electric Photon LP', 'Bullet 500', 'FZ 25 BS6',
       'Centuro O1', '42 Dual Tone', 'Ray Z', 'Duke 390', 'Jupiter BS6',
       'SP125', 'Shine 125 Drum', 'CD 100',
       'NTORQ 125 Super Soldier Edition', 'B8 Lithium Ion', 'Shine 100',
       'Glamour PGM Fi', '42 Dual Channel ABS Orion Red', 'Luna Super',
       'Jupiter ZX Disc BS6', 'Apache RTR 200 4V 2020',
       'Shine Celebration Edition', 'Scrambler Dual Tone', 'CD Deluxe',
       'Perak BS6', '42 Bobber Dual Channel ABS',
       'Avenger Street 160 BS6', 'Pulsar 200 NS', 'RC 390 2024',
       'Hness CB 350', 'Bullet Machismo A500', 'Ridge Plus', 'F77 Mach 2',
       'Scooty Pep Plus', 'XPulse 200T', 'Magnus Pro', 'Destini 125 VX',
       'Pulsar 125 Carbon Fibre Disc Split Seat', 'Alpha',
       'Davidson Iron 883', 'United Clovis 5.2', 'e-bike Wolf',
       'Pulsar 220 DTSFi', '42 Dual Channel ABS Cosmic Carbon',
       'Ninja 300 BS6 2022', 'RC 125 2020', 'Karizma R',
       'Classic 350 2021', 'RC 200', 'CT110 ES BS6', 'Super Meteor 650',
       'Shine', 'Dio BS6', 'Unicorn 160 BS6', 'Passion XTec',
       'NTORQ Super Squad Edition', 'Pulsar 150 Neon', 'Scooty Streak',
       'Access 125 Special Edition', 'Duke 200 2022',
       'Maestro Edge 125 BS6', 'Xtreme 160R 4V Connected 2.0',
       'Fascino 125 Fi', 'Jupiter 125 SmartXonnect', 'Apache RTR 200 4V',
       'S1 Pro Gen 3 3kWh', 'F 900 XR Pro', 'FZ-S FI V3 BS6', 'Perak',
       'CB350RS New Hue Edition', 'Pulsar 220F BS6',
       'Shine 125 Disc OBD2', 'SlingShot Plus', 'Ronin TD',
       'Xtreme 160R 4V Pro', 'XPulse 200 BS6', 'Pulsar 150 Neon BS6',
       'Raider 125', 'Destini 125', 'Apache RR 310 2020',
       'Apache RTR 180', 'Splendor Pro', 'Avenger 180 DTS-i', 'CB350 DLX',
       'RC 200 2020', 'Maestro Edge', 'Ignitor', 'Maestro Edge 125',
       'Magnus Ex', 'RC 125 2022', 'CBZ', 'Hornet',
       'Fascino 125 Fi Hybrid', 'Dominar 400', 'Xtreme 160R',
       'Raider iGO', 'YZF R15 V3 BS6', 'SP 160 Double Disc',
       'Davidson X440 Vivid', 'V-Strom 250', 'Vitpilen 250',
       'Apache RTR 200 4V ABS', '390 Adventure', 'Ninja 300R',
       'Svartpilen 250', 'Scrambler 400 X', 'Continental GT 650 Twin',
       'Discover 150 S', 'Rizta S', 'Fazer 125', 'Glamour',
       'Discover 125M', 'RC 125', 'Activa i', '450X Gen 3', 'Street Twin',
       'S1X 4 kWh', 'Adventure Single Headlight', 'Discover DTSi 150',
       'Destini 125 BS6', 'Star City', 'Dio 125 Smart',
       'Super Splendor IBS', 'Burgman Street',
       'Xpulse 200 4V Rally Edition', 'Montra', 'RC 390',
       'XL100 Comfort i-TOUCHstart BS6', 'E2go Lite', 'Himalayan 452',
       'Splendor Plus Black and Accent', 'W175 BS6 2023', 'Gusto 125',
       'Vitpilen 250 2020', 'Guerrilla 450 Flash', 'Firefox',
       'Xtreme 160R Stealth Edition', 'G 310 GS BS6', 'CT110X',
       'Pulsar 125', 'NTORQ 125 Race Edition BS6', 'Svartpilen 401 2024',
       'Decathlon', 'Schnell', 'Gold Star 650',
       'Pulsar 125 Carbon Fibre Disc Single Seat', 'Duke 250 2022',
       'Tiger Sport 660', 'Scooty Pep', 'Access 125 BS6', 'NX200 2025',
       'Imperiale 400 BS6', 'Aerox 155 Version S', 'Gixxer 150',
       'Pulsar NS400Z', 'Sport', 'S1 Pro Plus Gen 3 4kWh',
       'Xtreme 160R BS6', 'Glamour X 125 Disc', 'Svartpilen 250 2022',
       'Toronto', 'Shotgun 650', 'FZS 25',
       "forty two Jawa 42 dual channel ABS Haley's teal",
       'MT-15 Version 2.0 DLX 2025', 'HF Deluxe i3s', 'Storm 125',
       'CB Shine Limited Edition',
       'Apache RTR 200 Fi 4V Race Edition 2.0', 'Roadster 2025',
       'CT 125X', 'Sport BS6', 'Ninja 650R', 'Bullet 350 Twinspark',
       'Splendor iSmart 110 FI BS-VI', 'Svartpilen 250 2020',
       '2023 Activa 125 H-Smart', 'Jupiter Drum Alloy 2024',
       '2021 Dominar 400', 'MT', '2014',
       'FZ25 Monster Energy MotoGP Edition', 'Pulsar NS 160 BS6',
       'Avenis 125 Standard Edition', 'Fazer FI V2', 'Roadster X 4.5',
       'RayZR Street Rally 125 Fi Hybrid', 'Vieste 300', 'Fazer',
       'RS 125', 'V-Strom SX', 'RC 200 2022', 'Super Splendor XTEC',
       'Ladybird', 'Roadster Chrome', 'Pulsar 125 Neon Disc Single Seat',
       'iQube 09', 'Pulsar 125 Neon', 'Discover 150 F', 'Xtreme Sports',
       'Diavel 1260', 'Pulsar 200 NS ABS NS 200', 'Xpulse 200 4V Pro',
       'Avenis 125 Ride Connect Edition', 'Thunderbird X 500',
       'Gladiator', 'SR 150', 'Pulsar N150', 'G 310 RR Limited Edition',
       'Pulsar NS 200 BS6', 'Adventure Twin Headlight',
       'Super Splendor BS6', 'Avenger Street 220 BS6',
       'Meteor 350 Fireball', 'S1 Pro Gen 3 4kWh',
       '2023 Continental GT 650', 'Ronin DS', 'SR 250', 'Splendor iSmart',
       'Bullet Thunderbird X 350', 'Ronin 2025', 'Star City Plus',
       'Pulsar 150 Twin Disc BS6', '450 Plus',
       'Bullet Trials Works Replica 350', 'XPulse 210', 'Activa e',
       'Duke 125', 'Ronin TD Special Edition', 'SZ-RR V2', 'Maestro',
       'SZ-R'], dtype=object)

In [114]:
model_fix = {
    "forty two": "42",
    "forty two BS6": "42 BS6",
    "forty two Jawa 42 dual channel ABS Haley's teal": "42 Dual Channel ABS Haley's Teal",

    "Gixxer Gixxer SF 150": "Gixxer SF 150",
    "Pulsar 200 NS ABS NS 200": "Pulsar 200 NS ABS",

    "2023 Interceptor 650": "Interceptor 650",
    "2022 Meteor 350": "Meteor 350",
    "2021 Dominar 400": "Dominar 400",
    "2023 Continental GT 650": "Continental GT 650",
    "2023 Activa 125 H    Smart": "Activa 125 H    Smart",

    "nova": "Nova",
    "MT": "MT    15",
    "2014": "Splendor",
    "iQube 09": "iQube",

    "Davidson X440 Denim": "X440 Denim",
    "Davidson X440 S": "X440 S",
    "Davidson Street 750": "Street 750",
    "Davidson Street Rod": "Street Rod",
    "Davidson Iron 883": "Iron 883",

    "Urban Terrain Blitz Kids Cycle 16T": "Urban Terrain Blitz 16T",
    "United Clovis 5.2": "Clovis 5.2",
    "Ladybird": "Ladybird Cycle",
    "Montra": "Montra Cycle",
    "Toronto": "Toronto Cycle",
    "Decathlon": "Decathlon Cycle",
    "Schnell": "Schnell Cycle"
}

df['model_name'] = df['model_name'].replace(model_fix)

In [115]:
final_fix = {
    "Versys 650 BS6 2021": "Versys 650 BS6",
    "Dominar 250 2022": "Dominar 250",
    "Duke 125 2022": "Duke 125",
    "Duke 200 2024": "Duke 200",
    "Duke 250 2025": "Duke 250",
    "Speed 400 2025": "Speed 400",
    "Hunter 350 2025": "Hunter 350",
    "450S 2025": "450S",
    "390 Adventure 2022": "390 Adventure",
    "390 Adventure 2023": "390 Adventure",
    "250 Adventure 2022": "250 Adventure",
    "Ninja 300 BS6 2022": "Ninja 300 BS6",
    "W175 BS6 2023": "W175 BS6",
    "Z900 2022": "Z900",
    "Pulsar NS400Z 2025": "Pulsar NS400Z",
    "SR 160": "SR160",
    "SR 150": "SR150",
    "MT    15 Version 2.0 DLX 2025": "MT    15 Version 2.0 DLX",
    "MT    15 Ver 2.0": "MT    15 Version 2.0",
    "iQube Electric": "iQube",
    "FZ25": "FZ 25",
    "450X": "450X Gen 3",
    "Hornet": "Hornet 2.0"
}
df["model_name"] = df["model_name"].replace(final_fix)

In [116]:
df['model_name'].unique()

array(['Classic 500', 'Activa 125', 'Pulsar 220F', 'SR 125',
       'Pulsar NS 160', 'CB Hornet 160R ABS', 'Splendor Plus IBS i3s',
       'Versys 650 BS6', 'Interceptor 650', 'Pulsar 150 BS6',
       'Raider Split Seat', 'Thunderbird 350', 'Imperiale 400',
       'Destini 125 Xtec', 'CB350RS', 'Activa', 'FZ 25',
       '42 Bobber Black Mirror', 'FZ-S', 'Gixxer SF 250 BS6', 'V15',
       'Classic Signals Stormrider Sand', 'Jupiter', 'Duke 125',
       'East coast 7speed oldskool', 'EV Rorr EZ Sigma', 'Speed 400',
       'Continental GT 650', 'Hunter 350 Metro', 'F77 SuperStreet',
       'Jaunty Pro', 'Classic 350 Redditch Red', 'Wego', 'Pulsar 135LS',
       'YZF R15 V2', 'Falcon', 'Dio Standard', 'Activa 3G', 'Dominar 250',
       'Avenger 220 DTS-i', 'Hunk', 'Hornet 2.0', 'Splendor',
       'Pulsar 180', 'Centuro', 'Pulsar AS 150', 'Pulsar 220 DTSi',
       'NTORQ 125', 'Praise Pro', 'Activa 6G Dlx', 'FZ-X',
       'Apache RR 310 BTO', 'Pulsar 180 DTSi', 'Avenger Street 160',
       'NTORQ 125 Race XP', 'Glamour BS6', 'Pulsar 150 DTSi',
       'Meteor 350 Stellar', 'FZ-S FI V2', 'S1X Plus', 'Passion Pro',
       'CB Trigger', '450X Gen 3', 'R15M', 'CB Shine', 'XPulse 200T 4V',
       'Duke 200', 'Rizta Z', 'CB Shine SP', 'Activa 4G', 'Pulsar N250',
       'TRK 502 BS6', 'Classic Desert Storm', 'Pulsar NS125 BS6',
       'Platina 100 ES', 'Apache RTR 160 4V BS6', 'SP 125 BSVI',
       'Chetak Electric', 'Z900', 'Jupiter ZX',
       'Access 125 Ride Connect Edition', 'Pulsar N160',
       'Intruder 150 FI', 'Green Zing Electric', 'FZS 25 BS6',
       'Renegade Commando Mojave', 'Pulsar AS 200', 'G 310 R',
       'Bullet Electra', 'Jupiter Classic 110', 'CB Unicorn 160',
       'Himalayan 2021', 'S1 Pro', 'Xtreme 125R Dual Channel ABS',
       'Radeon', '450S', 'Avenger Cruise 220', 'Splendor Plus',
       'Duke 200 ABS', 'Pulsar N160 Dual Channel ABS', 'FZ-S FI Ver 4.0',
       'Passion Plus', 'R15 V4', 'CB Hornet 160R', 'Passion X Pro',
       'CB Unicorn', 'Thunderbird 500', 'FZ-S FI V3', 'Classic 350',
       'Duke 250', 'Apache RR 310', 'S1', 'Activa 6G', 'Livo Disc',
       'Hornet 2.0 Repsol Edition', 'Apache RTR 160 4V', 'Intruder 150',
       'G 310 GS', 'Chetak 3503', 'S1 Air 3kWh', 'Fascino S', 'iQube ST',
       '390 Adventure', 'Splendor Plus Xtec', 'Avenger Street 150',
       'Shine 125 Disc', 'Indie', 'Thunderbird X 350', '42',
       'Pulsar NS400Z', 'Jupiter 125', 'S1X 3 kWh', 'Aerox 155',
       'Pulsar 200 NS ABS', 'Meteor 350', '302R', 'Gixxer SF',
       'Access 125', '42 FJ', 'Dominar 400 ABS BS6', 'EV Rorr EZ',
       'Pulsar NS200', 'MT-15', 'G 310 RR', 'Avenger Street 180',
       'Bullet Standard 350', 'X440 Denim', 'Pulsar RS 200 BS6',
       'V1 Plus', 'FZ1', 'Dream Yuga', 'Passion Pro BS6', 'XPulse 200',
       'Avenger 200 DTS-i', 'Pulsar RS 200 ABS', 'S1 3kWh', 'RC 200 GP',
       'Himalayan', 'GS 150R', 'V1 Pro', 'Classic 350 BS VI', 'Achiever',
       'Radeon BS6', 'X440 S', 'RV 400', 'FZ16', 'Classic Stealth Black',
       'Meteor 350 Supernova', 'Shine 125', 'Jupiter ZX BS6',
       'Glamour 125 Drum', 'Pulsar RS 200', 'YZF R15 V3', 'Livo Drum',
       'Electric Optima CX2.0', 'RS 457',
       'CB350C DLX Pro Special Edition', 'Himalayan BS VI',
       'Chetak Premium 2023 Edition', 'MT-15 Ver 2.0', 'YZF R15 S V3.0',
       '350 Legacy Edition', 'Duke 250 2020', 'CB350 DLX Pro',
       'Hunter 350', 'Pulsar NS 125', 'HF Deluxe', 'Interceptor 650 Twin',
       'S1 Pro Gen 3', 'SR160', 'Xtreme 125R', 'Apache RTR 160',
       'Classic 350 Dual Channel BS6', 'Scram 411', 'SS125',
       'Hunter 350 Retro', 'Roadster Red', 'Pulsar N250 Dual Channel ABS',
       'Xtreme 125R Single Seat', 'Gixxer SF BS6', 'S1 Pro Gen2',
       'Thunderbird TwinSpark 350', 'Glamour 125', '42 BS6', 'Magnus',
       'RV400 BRZ', 'Activa 6G Std', 'Renegade Commando', 'Glamour Xtec',
       'Bear 650', 'ZX 125 BS6', 'Activa 5G Limited Edition',
       'Roadster Dark', 'RX 135', 'Xtreme 160R 4V Standard',
       'Activa 125 BS6', 'Unicorn Dazzler', 'S1 Air', 'Jawa BS6',
       'Apache RTR 200 4V ABS Race Edition 2.0', 'TNT 600 i',
       'Urban Terrain Blitz 16T', 'Pleasure Plus XTec', 'Adventure Matte',
       'NTORQ 125 Race Edition', 'Tiger 900 Rally', 'Scooty Pep Plus BS6',
       'Apache RTR 160 4V Special Edition', '250 Adventure',
       'RV400 Stealth Black Limited Edition', 'Destini Prime',
       'Shine BS6', 'Saluto 125', 'iQube', 'Gixxer SF 150',
       'Apache RTR 310', 'Discover 100 DTS-Si', 'Discover 100',
       'Raider SX', 'Bullet 350', 'Platina 100', 'Chetak 3501 Standard',
       'Scrambler Single Tone', 'Z650 ABS', 'Trek', 'XBlade',
       'Pulsar 150 Twin Disc', 'Glamour 125 Disc', 'Chetak Urbane',
       'Bullet 350 ES BS6', 'Discover 125', 'Gixxer SF 250', 'SXR 160',
       'CD 100SS', 'Jawa', 'Apache RTR 200 4V 2022', 'Apache RR 310 2025',
       'Himalayan 450', 'Pulsar 150', 'Pleasure Plus BS6', 'Nova',
       'CB125 Hornet', 'CBZ Xtreme', '2022 CB300R',
       'Hness Anniversary Edition', 'Livo 110', 'Aviator', 'iQube S',
       'Avon Charge', 'V12', 'VXL 125',
       'Splendor Plus i3s Black and Accent', 'HF Deluxe BS6',
       'Xpulse 200 4V', 'CB200X', 'Avenger Cruise 220 BS6', 'Activa 5G',
       'CBR 150R', 'Pleasure', 'Kratos R', 'Dio', 'Classic Gunmetal Grey',
       'CBF Stunner', 'Karizma XMR', 'Crossfire 500 X',
       'Adventure Matte 2024', 'S1 X Gen 3 4kWh', 'Pulsar 125 Split Seat',
       '42 Dual Channel ABS AllStar Black', 'Classic 350 Redditch Green',
       'Passion Pro i3s', 'FZ', 'SXL 125', 'S1X', 'CB300R', 'Dream Neo',
       'FZ FI V2', 'Street 750', 'Fascino', 'Avenger Street 220',
       'Classic Chrome', 'Cygnus Ray ZR', 'Street Rod', 'MT-15 BS6',
       '390 Adventure X 2025', 'SZ-RR', 'Raider Black Panther Edition',
       'Unicorn', 'XPulse 200T BS6', 'Grazia 125 BS6',
       'Electric Photon LP', 'Bullet 500', 'FZ 25 BS6', 'Centuro O1',
       '42 Dual Tone', 'Ray Z', 'Duke 390', 'Jupiter BS6', 'SP125',
       'Shine 125 Drum', 'CD 100', 'NTORQ 125 Super Soldier Edition',
       'B8 Lithium Ion', 'Shine 100', 'Glamour PGM Fi',
       '42 Dual Channel ABS Orion Red', 'Luna Super',
       'Jupiter ZX Disc BS6', 'Apache RTR 200 4V 2020',
       'Shine Celebration Edition', 'Scrambler Dual Tone', 'CD Deluxe',
       'Perak BS6', '42 Bobber Dual Channel ABS',
       'Avenger Street 160 BS6', 'Pulsar 200 NS', 'RC 390 2024',
       'Hness CB 350', 'Bullet Machismo A500', 'Ridge Plus', 'F77 Mach 2',
       'Scooty Pep Plus', 'XPulse 200T', 'Magnus Pro', 'Destini 125 VX',
       'Pulsar 125 Carbon Fibre Disc Split Seat', 'Alpha', 'Iron 883',
       'Clovis 5.2', 'e-bike Wolf', 'Pulsar 220 DTSFi',
       '42 Dual Channel ABS Cosmic Carbon', 'Ninja 300 BS6',
       'RC 125 2020', 'Karizma R', 'Classic 350 2021', 'RC 200',
       'CT110 ES BS6', 'Super Meteor 650', 'Shine', 'Dio BS6',
       'Unicorn 160 BS6', 'Passion XTec', 'NTORQ Super Squad Edition',
       'Pulsar 150 Neon', 'Scooty Streak', 'Access 125 Special Edition',
       'Duke 200 2022', 'Maestro Edge 125 BS6',
       'Xtreme 160R 4V Connected 2.0', 'Fascino 125 Fi',
       'Jupiter 125 SmartXonnect', 'Apache RTR 200 4V',
       'S1 Pro Gen 3 3kWh', 'F 900 XR Pro', 'FZ-S FI V3 BS6', 'Perak',
       'CB350RS New Hue Edition', 'Pulsar 220F BS6',
       'Shine 125 Disc OBD2', 'SlingShot Plus', 'Ronin TD',
       'Xtreme 160R 4V Pro', 'XPulse 200 BS6', 'Pulsar 150 Neon BS6',
       'Raider 125', 'Destini 125', 'Apache RR 310 2020',
       'Apache RTR 180', 'Splendor Pro', 'Avenger 180 DTS-i', 'CB350 DLX',
       'RC 200 2020', 'Maestro Edge', 'Ignitor', 'Maestro Edge 125',
       'Magnus Ex', 'RC 125 2022', 'CBZ', 'Fascino 125 Fi Hybrid',
       'Dominar 400', 'Xtreme 160R', 'Raider iGO', 'YZF R15 V3 BS6',
       'SP 160 Double Disc', 'Davidson X440 Vivid', 'V-Strom 250',
       'Vitpilen 250', 'Apache RTR 200 4V ABS', 'Ninja 300R',
       'Svartpilen 250', 'Scrambler 400 X', 'Continental GT 650 Twin',
       'Discover 150 S', 'Rizta S', 'Fazer 125', 'Glamour',
       'Discover 125M', 'RC 125', 'Activa i', 'Street Twin', 'S1X 4 kWh',
       'Adventure Single Headlight', 'Discover DTSi 150',
       'Destini 125 BS6', 'Star City', 'Dio 125 Smart',
       'Super Splendor IBS', 'Burgman Street',
       'Xpulse 200 4V Rally Edition', 'Montra Cycle', 'RC 390',
       'XL100 Comfort i-TOUCHstart BS6', 'E2go Lite', 'Himalayan 452',
       'Splendor Plus Black and Accent', 'W175 BS6', 'Gusto 125',
       'Vitpilen 250 2020', 'Guerrilla 450 Flash', 'Firefox',
       'Xtreme 160R Stealth Edition', 'G 310 GS BS6', 'CT110X',
       'Pulsar 125', 'NTORQ 125 Race Edition BS6', 'Svartpilen 401 2024',
       'Decathlon Cycle', 'Schnell Cycle', 'Gold Star 650',
       'Pulsar 125 Carbon Fibre Disc Single Seat', 'Duke 250 2022',
       'Tiger Sport 660', 'Scooty Pep', 'Access 125 BS6', 'NX200 2025',
       'Imperiale 400 BS6', 'Aerox 155 Version S', 'Gixxer 150', 'Sport',
       'S1 Pro Plus Gen 3 4kWh', 'Xtreme 160R BS6', 'Glamour X 125 Disc',
       'Svartpilen 250 2022', 'Toronto Cycle', 'Shotgun 650', 'FZS 25',
       "42 Dual Channel ABS Haley's Teal", 'MT-15 Version 2.0 DLX 2025',
       'HF Deluxe i3s', 'Storm 125', 'CB Shine Limited Edition',
       'Apache RTR 200 Fi 4V Race Edition 2.0', 'Roadster 2025',
       'CT 125X', 'Sport BS6', 'Ninja 650R', 'Bullet 350 Twinspark',
       'Splendor iSmart 110 FI BS-VI', 'Svartpilen 250 2020',
       '2023 Activa 125 H-Smart', 'Jupiter Drum Alloy 2024', 'MT    15',
       'FZ25 Monster Energy MotoGP Edition', 'Pulsar NS 160 BS6',
       'Avenis 125 Standard Edition', 'Fazer FI V2', 'Roadster X 4.5',
       'RayZR Street Rally 125 Fi Hybrid', 'Vieste 300', 'Fazer',
       'RS 125', 'V-Strom SX', 'RC 200 2022', 'Super Splendor XTEC',
       'Ladybird Cycle', 'Roadster Chrome',
       'Pulsar 125 Neon Disc Single Seat', 'Pulsar 125 Neon',
       'Discover 150 F', 'Xtreme Sports', 'Diavel 1260',
       'Xpulse 200 4V Pro', 'Avenis 125 Ride Connect Edition',
       'Thunderbird X 500', 'Gladiator', 'SR150', 'Pulsar N150',
       'G 310 RR Limited Edition', 'Pulsar NS 200 BS6',
       'Adventure Twin Headlight', 'Super Splendor BS6',
       'Avenger Street 220 BS6', 'Meteor 350 Fireball',
       'S1 Pro Gen 3 4kWh', 'Ronin DS', 'SR 250', 'Splendor iSmart',
       'Bullet Thunderbird X 350', 'Ronin 2025', 'Star City Plus',
       'Pulsar 150 Twin Disc BS6', '450 Plus',
       'Bullet Trials Works Replica 350', 'XPulse 210', 'Activa e',
       'Ronin TD Special Edition', 'SZ-RR V2', 'Maestro', 'SZ-R'],
      dtype=object)

In [117]:
final_model_fix = {
    "Duke 250 2020": "Duke 250",
    "Apache RTR 200 4V 2022": "Apache RTR 200 4V",
    "Apache RR 310 2025": "Apache RR 310",
    "Apache RR 310 2020": "Apache RR 310",
    "RC 125 2020": "RC 125",
    "RC 125 2022": "RC 125",
    "RC 200 2022": "RC 200",
    "RC 200 2020": "RC 200",
    "RC 390 2024": "RC 390",
    "390 Adventure X 2025": "390 Adventure X",
    "NX200 2025": "NX200",
    "Shotgun 650": "Shotgun 650 Twin",
    "SR 250": "SR250",
    "SR150": "SR 150",
    "SR160": "SR 160",
    "MT    15 Version 2.0": "MT    15 Version 2.0 DLX",
    "Himalayan 2021": "Himalayan",
    "Classic 350 2021": "Classic 350",
    "Meteor 350 Fireball": "Meteor 350",
    "2022 CB300R": "CB300R",
    "Activa 125 H    Smart": "Activa 125",
    "FZ25 Monster Energy MotoGP Edition": "FZ 25",
    "Pulsar NS 160 BS6": "Pulsar NS 160",
    "Pulsar NS 200 BS6": "Pulsar NS200",
    "Discover 100 DTS    Si": "Discover 100 DTSi",
    "CB350C DLX Pro Special Edition": "CB350C DLX Pro",
    "Imperiale 400 BS6": "Imperiale 400",
    "F 900 XR Pro": "F 900 XR",
    "Z650 ABS": "Z650"
}

df["model_name"] = df["model_name"].replace(final_model_fix)

In [118]:
model_fix_master = {

    # Remove year noise
    "Versys 650 BS6 2021": "Versys 650 BS6",
    "Dominar 250 2022": "Dominar 250",
    "Duke 125 2022": "Duke 125",
    "Duke 200 2024": "Duke 200",
    "Duke 250 2025": "Duke 250",
    "Speed 400 2025": "Speed 400",
    "Hunter 350 2025": "Hunter 350",
    "450S 2025": "450S",
    "390 Adventure 2022": "390 Adventure",
    "390 Adventure 2023": "390 Adventure",
    "250 Adventure 2022": "250 Adventure",
    "Ninja 300 BS6 2022": "Ninja 300 BS6",
    "W175 BS6 2023": "W175 BS6",
    "Z900 2022": "Z900",
    "Pulsar NS400Z 2025": "Pulsar NS400Z",

    # Jawa standardization
    "42": "Jawa 42",
    "42 FJ": "Jawa 42 FJ",
    "42 BS6": "Jawa 42 BS6",
    "42 Dual Tone": "Jawa 42 Dual Tone",
    "42 Bobber Black Mirror": "Jawa 42 Bobber Black Mirror",
    "42 Bobber Dual Channel ABS": "Jawa 42 Bobber Dual Channel ABS",
    "42 Dual Channel ABS Cosmic Carbon": "Jawa 42 Dual Channel ABS Cosmic Carbon",
    "42 Dual Channel ABS Orion Red": "Jawa 42 Dual Channel ABS Orion Red",
    "42 Dual Channel ABS AllStar Black": "Jawa 42 Dual Channel ABS AllStar Black",
    "42 Dual Channel ABS Haley's Teal": "Jawa 42 Dual Channel ABS Haley's Teal",
    "Jawa BS6": "Jawa 42 BS6",
    "350 Legacy Edition": "Jawa 350 Legacy Edition",

    # Spacing / formatting fixes
    "FZ1": "FZ 1",
    "SR250": "SR 250",
    "SR160": "SR 160",
    "FZS 25": "FZ    S 25",

    # Variant noise removal
    "FZ 25 BS6": "FZ 25",
    "MT    15 BS6": "MT    15",
    "Apache RTR 200 4V 2020": "Apache RTR 200 4V",
    "Ninja 300 BS6": "Ninja 300",

    # Other cleanup
    "450X": "450X Gen 3",
    "Hornet": "Hornet 2.0"
}
df["model_name"] = df["model_name"].replace(model_fix_master)

In [119]:
df['city'].unique()

array([' Mumbai', ' Bangalore', 'Pune', ' Pune', 'Bangalore', 'Mumbai',
       'South Delhi', 'Visakhapatnam', ' Saharanpur', 'Hyderabad',
       ' Chennai', ' Darjeeling', 'Ghaziabad', 'Navi Mumbai', ' Jaipur',
       'Tumkur', ' Varanasi', 'Ahmedabad', 'Khammam', 'Gurgaon',
       ' North West Delhi', ' Gurdaspur', ' Bapatla', 'Coimbatore',
       ' Ballia', 'Vadodara', 'Guwahati', 'Pimpri-Chinchwad',
       'Bhubaneshwar', 'Jaipur', 'Vellore', ' Mandya', 'Chennai',
       ' Hyderabad', 'Nagpur', 'Dharwad', ' Satara', 'Ajmer', 'Medchal',
       'Kanpur', 'West Delhi', 'Kolkata', ' Faridabad', 'New Delhi',
       'Puri', ' Gautam Buddha Nagar', 'Thane', 'Sirsa', 'Satara',
       'Raigad', ' Thane', ' Trivandrum', 'Cuttack', ' Chengalpattu',
       ' Jodhpur', 'Bhopal', ' North 24 Parganas', 'Noida', ' Barpeta',
       ' Sirsa', 'Bhandara', ' Vijayanagara', 'Lakhisarai', 'Lucknow',
       ' Rangareddy', 'Shahdara', ' Vadodara', ' North Goa', 'East Delhi',
       ' New Delhi', ' Raigad', 'Thrissur', 'Ahmednagar', 'Erode',
       'Indore', 'Dehradun', 'Tirupati', 'Greater Noida', 'Chengalpattu',
       'Jogulamba Gadwal', 'Rupnagar', 'Nagaon', ' Ernakulam', 'Patna',
       'Tiruvannamalai', 'Palghar', ' South West Delhi', ' Kottayam',
       'Surat', 'Hoshiarpur', ' Ranipet', 'Faridabad', 'Ludhiana',
       ' Bharuch', 'Bulandshahr', 'North East Delhi', 'Chhindwara',
       ' Paschim Bardhaman', 'Kota', 'North Delhi', 'Mahabubnagar',
       ' Beed', 'Amritsar', ' Hanumangarh', 'Valsad', ' Dibrugarh',
       ' Sangli', 'Bilaspur', 'Kolhapur', 'Kanpur Nagar',
       'Tiruchirappalli', 'Mysore', 'Bareilly', 'Burhanpur', ' Dehradun',
       'Chitradurga', ' Nalanda', ' South Delhi', 'Alwar', 'Cuddalore',
       'Jabalpur', 'Silvassa', 'Mangalore', 'Dhule', 'Jalgaon', 'Jodhpur',
       'Jhunjhunu', ' Kannur', ' Belgaum', ' North East Delhi', 'Nanded',
       ' Mandla', 'Bathinda', 'Jalna', 'Bharuch', ' Kanchipuram',
       ' Palghar', 'Tiruvallur', ' Hooghly', ' Tiruvallur', 'Ratnagiri',
       ' Allahabad', 'Sabar Kantha', ' Viluppuram', 'Mathura', 'Hooghly',
       ' Suryapet', ' Mohali', 'North 24 Parganas', 'Kozhikode',
       'Allahabad', 'Agra', ' Sri Ganganagar', 'Namakkal', ' Idukki',
       ' Cuttack', 'Gadchiroli', 'Vijayanagara', 'Trivandrum',
       ' Palakkad', 'Kanpur Dehat', ' Lucknow', ' Kushinagar', ' Hapur',
       ' Tiruchirappalli', ' Sangareddy', ' Erode', 'Palwal',
       ' Firozabad', ' East Godavari', 'Ranipet', ' Patiala', 'Madurai',
       'Nandyal', ' East Delhi', ' Gandhinagar', 'Badaun', 'Sehore',
       'Guntur', ' Kanyakumari', 'Mohali', ' Gurgaon', 'Gandhinagar',
       'Hathras', 'Karur', 'Rajkot', 'Chikballapur', ' Yavatmal',
       ' Valsad', 'Dewas', ' Pondicherry', 'Gulbarga', 'Nashik',
       'Rangareddy', 'Mandi', 'Vaishali', ' Salem', ' South East Delhi',
       'Nellore', 'Aurangabad', 'Salem', 'South West Delhi', ' Anantapur',
       'Palakkad', ' Chickmagalur', ' Ramanagara', 'Bellary', ' Gadag',
       'Chhatrapati Sambhajinagar', 'Dindigul', 'Howrah', 'Rewari',
       ' West Medinipur', ' Rajkot', ' Malda', 'Panipat', ' Ghaziabad',
       ' Ahmedabad', ' Nadia', 'Kanyakumari', ' Medchal-Malkajgiri',
       'Margao', ' Dharmapuri', 'Amravati', 'Meerut', ' Coimbatore',
       'North West Delhi', ' Churu', ' Tenkasi', ' Kokrajhar',
       'Gautam Buddha Nagar', ' Uttara Kannada', 'Malda', 'Prayagraj',
       'Jamnagar', 'Vijayawada', 'Mayiladuthurai', ' Buldhana', ' Nagaur',
       'Dakshina Kannada', 'Muzaffarnagar', 'Thoothukudi',
       ' South 24 Parganas', 'Anantapur', 'Hisar', 'Etawah', ' Palwal',
       ' Visakhapatnam', ' YSR', 'Nalgonda', 'Pondicherry', 'Jind',
       'Jajpur', 'Patiala', ' Thrissur', 'Varanasi', 'Wanaparthy',
       ' Deoria', ' Shahdara', 'Ballia', ' Nellore', 'Basti',
       ' Malappuram', 'Latur', 'Bardhaman', 'Ernakulam', ' Cuddalore',
       ' Kadapa', 'Kanchipuram', ' Kapurthala', ' Jammu', 'Haveri',
       ' Tumkur', ' Jagatsinghapur', 'Dhanbad', ' Bardhaman', ' Jalgaon',
       'Sangli', ' Sindhudurg', ' Guntur', 'Mahesana', 'Koppal', ' Pali',
       'Ambala', 'Jammu', 'Paschim Bardhaman', 'Nizamabad', ' Ganjam',
       'Hamirpur', 'Suryapet', 'Ujjain', 'Kotputli-Behror', 'Shimla',
       ' Agra', 'South East Delhi', ' West Siang', ' Virudhunagar',
       'Bankura', ' Howrah', 'Raipur', ' Dharwad', 'Tinsukia', 'Belgaum',
       'Medchal-Malkajgiri', 'Morigaon', 'Barabanki', ' Guna', 'Kadapa',
       'Karnal', 'Muzaffarpur', 'Purulia', ' Tirupur',
       ' Yadadri Bhuvanagiri', ' Solapur', 'Davangere', 'Ratlam',
       'Haridwar', ' Jhunjhunu', ' Kheda', ' West Delhi', 'Gorakhpur',
       'Chittoor', 'Kannauj', ' Purulia'], dtype=object)

In [120]:
import re

df["city"] = (
    df["city"]
    .astype(str)
    .str.strip()                           # remove starting / ending spaces
    .str.replace(r"\s+", " ", regex=True) # remove double / triple spaces
    .str.replace("    ", " ", regex=False)   # Medchal    Malkajgiri → Medchal Malkajgiri
    .str.replace(r"\s{2,}", " ", regex=True)
    .str.title()                          # Proper case: mUMbai → Mumbai
)
city_fix = {
    "Allahabad": "Prayagraj",
    "Faizabad": "Ayodhya",
    "Gurgaon": "Gurugram",
    "Bardhaman": "Burdwan",
    "Medchal Malkajgiri": "Medchal–Malkajgiri",
    "North 24 Parganas": "North 24 Parganas",
    "South 24 Parganas": "South 24 Parganas",
    "Paschim Bardhaman": "Paschim Bardhaman",
    "Purba Bardhaman": "Purba Bardhaman",
    "Hooghly": "Hooghly"
}

df["city"] = df["city"].replace(city_fix)

In [121]:
df['city'].unique()

array(['Mumbai', 'Bangalore', 'Pune', 'South Delhi', 'Visakhapatnam',
       'Saharanpur', 'Hyderabad', 'Chennai', 'Darjeeling', 'Ghaziabad',
       'Navi Mumbai', 'Jaipur', 'Tumkur', 'Varanasi', 'Ahmedabad',
       'Khammam', 'Gurugram', 'North West Delhi', 'Gurdaspur', 'Bapatla',
       'Coimbatore', 'Ballia', 'Vadodara', 'Guwahati', 'Pimpri-Chinchwad',
       'Bhubaneshwar', 'Vellore', 'Mandya', 'Nagpur', 'Dharwad', 'Satara',
       'Ajmer', 'Medchal', 'Kanpur', 'West Delhi', 'Kolkata', 'Faridabad',
       'New Delhi', 'Puri', 'Gautam Buddha Nagar', 'Thane', 'Sirsa',
       'Raigad', 'Trivandrum', 'Cuttack', 'Chengalpattu', 'Jodhpur',
       'Bhopal', 'North 24 Parganas', 'Noida', 'Barpeta', 'Bhandara',
       'Vijayanagara', 'Lakhisarai', 'Lucknow', 'Rangareddy', 'Shahdara',
       'North Goa', 'East Delhi', 'Thrissur', 'Ahmednagar', 'Erode',
       'Indore', 'Dehradun', 'Tirupati', 'Greater Noida',
       'Jogulamba Gadwal', 'Rupnagar', 'Nagaon', 'Ernakulam', 'Patna',
       'Tiruvannamalai', 'Palghar', 'South West Delhi', 'Kottayam',
       'Surat', 'Hoshiarpur', 'Ranipet', 'Ludhiana', 'Bharuch',
       'Bulandshahr', 'North East Delhi', 'Chhindwara',
       'Paschim Bardhaman', 'Kota', 'North Delhi', 'Mahabubnagar', 'Beed',
       'Amritsar', 'Hanumangarh', 'Valsad', 'Dibrugarh', 'Sangli',
       'Bilaspur', 'Kolhapur', 'Kanpur Nagar', 'Tiruchirappalli',
       'Mysore', 'Bareilly', 'Burhanpur', 'Chitradurga', 'Nalanda',
       'Alwar', 'Cuddalore', 'Jabalpur', 'Silvassa', 'Mangalore', 'Dhule',
       'Jalgaon', 'Jhunjhunu', 'Kannur', 'Belgaum', 'Nanded', 'Mandla',
       'Bathinda', 'Jalna', 'Kanchipuram', 'Tiruvallur', 'Hooghly',
       'Ratnagiri', 'Prayagraj', 'Sabar Kantha', 'Viluppuram', 'Mathura',
       'Suryapet', 'Mohali', 'Kozhikode', 'Agra', 'Sri Ganganagar',
       'Namakkal', 'Idukki', 'Gadchiroli', 'Palakkad', 'Kanpur Dehat',
       'Kushinagar', 'Hapur', 'Sangareddy', 'Palwal', 'Firozabad',
       'East Godavari', 'Patiala', 'Madurai', 'Nandyal', 'Gandhinagar',
       'Badaun', 'Sehore', 'Guntur', 'Kanyakumari', 'Hathras', 'Karur',
       'Rajkot', 'Chikballapur', 'Yavatmal', 'Dewas', 'Pondicherry',
       'Gulbarga', 'Nashik', 'Mandi', 'Vaishali', 'Salem',
       'South East Delhi', 'Nellore', 'Aurangabad', 'Anantapur',
       'Chickmagalur', 'Ramanagara', 'Bellary', 'Gadag',
       'Chhatrapati Sambhajinagar', 'Dindigul', 'Howrah', 'Rewari',
       'West Medinipur', 'Malda', 'Panipat', 'Nadia',
       'Medchal-Malkajgiri', 'Margao', 'Dharmapuri', 'Amravati', 'Meerut',
       'Churu', 'Tenkasi', 'Kokrajhar', 'Uttara Kannada', 'Jamnagar',
       'Vijayawada', 'Mayiladuthurai', 'Buldhana', 'Nagaur',
       'Dakshina Kannada', 'Muzaffarnagar', 'Thoothukudi',
       'South 24 Parganas', 'Hisar', 'Etawah', 'Ysr', 'Nalgonda', 'Jind',
       'Jajpur', 'Wanaparthy', 'Deoria', 'Basti', 'Malappuram', 'Latur',
       'Burdwan', 'Kadapa', 'Kapurthala', 'Jammu', 'Haveri',
       'Jagatsinghapur', 'Dhanbad', 'Sindhudurg', 'Mahesana', 'Koppal',
       'Pali', 'Ambala', 'Nizamabad', 'Ganjam', 'Hamirpur', 'Ujjain',
       'Kotputli-Behror', 'Shimla', 'West Siang', 'Virudhunagar',
       'Bankura', 'Raipur', 'Tinsukia', 'Morigaon', 'Barabanki', 'Guna',
       'Karnal', 'Muzaffarpur', 'Purulia', 'Tirupur',
       'Yadadri Bhuvanagiri', 'Solapur', 'Davangere', 'Ratlam',
       'Haridwar', 'Kheda', 'Gorakhpur', 'Chittoor', 'Kannauj'],
      dtype=object)

In [122]:
city_fix_final = {
    "Bhubaneshwar": "Bhubaneswar",
    "Trivandrum": "Thiruvananthapuram",
    "Belgaum": "Belagavi",
    "Bellary": "Ballari",
    "Gulbarga": "Kalaburagi",
    "Chhatrapati Sambhajinagar": "Aurangabad",
    "Burdwan": "Bardhaman",
    "Ysr": "YSR Kadapa",
    "Pondicherry": "Puducherry",
    "Gautam Buddha Nagar": "Noida",
    "Kotputli Behror": "Kotputli–Behror",
    "Sabar Kantha": "Sabarkantha",
    "Viluppuram": "Viluppuram",
    "Yadadri Bhuvanagiri": "Yadadri Bhuvanagiri",
    "Medchal–Malkajgiri": "Medchal–Malkajgiri"
}

df["city"] = df["city"].replace(city_fix_final)

In [123]:
df['city'].unique()

array(['Mumbai', 'Bangalore', 'Pune', 'South Delhi', 'Visakhapatnam',
       'Saharanpur', 'Hyderabad', 'Chennai', 'Darjeeling', 'Ghaziabad',
       'Navi Mumbai', 'Jaipur', 'Tumkur', 'Varanasi', 'Ahmedabad',
       'Khammam', 'Gurugram', 'North West Delhi', 'Gurdaspur', 'Bapatla',
       'Coimbatore', 'Ballia', 'Vadodara', 'Guwahati', 'Pimpri-Chinchwad',
       'Bhubaneswar', 'Vellore', 'Mandya', 'Nagpur', 'Dharwad', 'Satara',
       'Ajmer', 'Medchal', 'Kanpur', 'West Delhi', 'Kolkata', 'Faridabad',
       'New Delhi', 'Puri', 'Noida', 'Thane', 'Sirsa', 'Raigad',
       'Thiruvananthapuram', 'Cuttack', 'Chengalpattu', 'Jodhpur',
       'Bhopal', 'North 24 Parganas', 'Barpeta', 'Bhandara',
       'Vijayanagara', 'Lakhisarai', 'Lucknow', 'Rangareddy', 'Shahdara',
       'North Goa', 'East Delhi', 'Thrissur', 'Ahmednagar', 'Erode',
       'Indore', 'Dehradun', 'Tirupati', 'Greater Noida',
       'Jogulamba Gadwal', 'Rupnagar', 'Nagaon', 'Ernakulam', 'Patna',
       'Tiruvannamalai', 'Palghar', 'South West Delhi', 'Kottayam',
       'Surat', 'Hoshiarpur', 'Ranipet', 'Ludhiana', 'Bharuch',
       'Bulandshahr', 'North East Delhi', 'Chhindwara',
       'Paschim Bardhaman', 'Kota', 'North Delhi', 'Mahabubnagar', 'Beed',
       'Amritsar', 'Hanumangarh', 'Valsad', 'Dibrugarh', 'Sangli',
       'Bilaspur', 'Kolhapur', 'Kanpur Nagar', 'Tiruchirappalli',
       'Mysore', 'Bareilly', 'Burhanpur', 'Chitradurga', 'Nalanda',
       'Alwar', 'Cuddalore', 'Jabalpur', 'Silvassa', 'Mangalore', 'Dhule',
       'Jalgaon', 'Jhunjhunu', 'Kannur', 'Belagavi', 'Nanded', 'Mandla',
       'Bathinda', 'Jalna', 'Kanchipuram', 'Tiruvallur', 'Hooghly',
       'Ratnagiri', 'Prayagraj', 'Sabarkantha', 'Viluppuram', 'Mathura',
       'Suryapet', 'Mohali', 'Kozhikode', 'Agra', 'Sri Ganganagar',
       'Namakkal', 'Idukki', 'Gadchiroli', 'Palakkad', 'Kanpur Dehat',
       'Kushinagar', 'Hapur', 'Sangareddy', 'Palwal', 'Firozabad',
       'East Godavari', 'Patiala', 'Madurai', 'Nandyal', 'Gandhinagar',
       'Badaun', 'Sehore', 'Guntur', 'Kanyakumari', 'Hathras', 'Karur',
       'Rajkot', 'Chikballapur', 'Yavatmal', 'Dewas', 'Puducherry',
       'Kalaburagi', 'Nashik', 'Mandi', 'Vaishali', 'Salem',
       'South East Delhi', 'Nellore', 'Aurangabad', 'Anantapur',
       'Chickmagalur', 'Ramanagara', 'Ballari', 'Gadag', 'Dindigul',
       'Howrah', 'Rewari', 'West Medinipur', 'Malda', 'Panipat', 'Nadia',
       'Medchal-Malkajgiri', 'Margao', 'Dharmapuri', 'Amravati', 'Meerut',
       'Churu', 'Tenkasi', 'Kokrajhar', 'Uttara Kannada', 'Jamnagar',
       'Vijayawada', 'Mayiladuthurai', 'Buldhana', 'Nagaur',
       'Dakshina Kannada', 'Muzaffarnagar', 'Thoothukudi',
       'South 24 Parganas', 'Hisar', 'Etawah', 'YSR Kadapa', 'Nalgonda',
       'Jind', 'Jajpur', 'Wanaparthy', 'Deoria', 'Basti', 'Malappuram',
       'Latur', 'Bardhaman', 'Kadapa', 'Kapurthala', 'Jammu', 'Haveri',
       'Jagatsinghapur', 'Dhanbad', 'Sindhudurg', 'Mahesana', 'Koppal',
       'Pali', 'Ambala', 'Nizamabad', 'Ganjam', 'Hamirpur', 'Ujjain',
       'Kotputli-Behror', 'Shimla', 'West Siang', 'Virudhunagar',
       'Bankura', 'Raipur', 'Tinsukia', 'Morigaon', 'Barabanki', 'Guna',
       'Karnal', 'Muzaffarpur', 'Purulia', 'Tirupur',
       'Yadadri Bhuvanagiri', 'Solapur', 'Davangere', 'Ratlam',
       'Haridwar', 'Kheda', 'Gorakhpur', 'Chittoor', 'Kannauj'],
      dtype=object)

In [124]:
df['bike_name'].unique()

array(['Royal Enfield Classic 500', 'Honda Activa 125',
       'Bajaj Pulsar 220F', 'Keeway SR 125', 'Bajaj Pulsar NS 160',
       'Honda CB Hornet 160R ABS', 'Hero Splendor Plus IBS i3s',
       'Kawasaki Versys 650 BS6 2021',
       'Royal Enfield 2023 Interceptor 650', 'Bajaj Pulsar 150 BS6',
       'TVS Raider Split Seat', 'Royal Enfield Thunderbird 350',
       'Benelli Imperiale 400', 'Hero Destini 125 Xtec', 'Honda CB350RS',
       'Honda Activa', 'Yamaha FZ25', 'Jawa 42 Bobber Black Mirror',
       'Yamaha FZ-S', 'Suzuki Gixxer SF 250 BS6', 'Bajaj V15',
       'Royal Enfield Classic Signals Stormrider Sand', 'TVS Jupiter',
       'KTM Duke 125 2022', 'Bicycle  East coast 7speed oldskool',
       'Oben EV Rorr EZ Sigma', 'Triumph Speed 400',
       'Royal Enfield Continental GT 650',
       'Royal Enfield Hunter 350 Metro', 'Ultraviolette F77 SuperStreet',
       'Amo Jaunty Pro', 'Royal Enfield Classic 350 Redditch Red',
       'TVS Wego', 'Bajaj Pulsar 135LS', 'Yamaha YZF R15 V2',
       'Benling Falcon', 'Honda Dio Standard', 'Honda Activa 3G',
       'Bajaj Dominar 250', 'Bajaj Avenger 220 DTS-i', 'Hero Hunk',
       'Honda Hornet 2.0', 'Hero Splendor', 'Bajaj Pulsar 180',
       'Mahindra Centuro', 'Bajaj Pulsar AS 150', 'Bajaj Pulsar 220 DTSi',
       'TVS NTORQ 125', 'Okinawa Praise Pro', 'Honda Activa 6G Dlx',
       'Yamaha FZ-X', 'TVS Apache RR 310 BTO', 'Bajaj Pulsar 180 DTSi',
       'Bajaj Avenger Street 160', 'TVS NTORQ 125 Race XP',
       'Hero Glamour BS6', 'Bajaj Pulsar 150 DTSi',
       'Royal Enfield Meteor 350 Stellar', 'Yamaha FZ-S FI V2',
       'Ola S1X Plus', 'Hero Passion Pro', 'Honda CB Trigger',
       'Ather 450X', 'Yamaha R15M', 'Honda CB Shine',
       'Hero XPulse 200T 4V', 'KTM Duke 200 2024', 'Ather Rizta Z',
       'Honda CB Shine SP', 'Honda Activa 4G', 'Bajaj Pulsar N250',
       'Benelli TRK 502 BS6', 'Royal Enfield Classic Desert Storm',
       'Bajaj Pulsar NS125 BS6', 'Bajaj Platina 100 ES',
       'TVS Apache RTR 160 4V BS6', 'Honda SP 125 BSVI',
       'Bajaj Chetak Electric', 'Kawasaki Z900 2022', 'TVS Jupiter ZX',
       'Suzuki Access 125 Ride Connect Edition', 'Bajaj Pulsar N160',
       'Suzuki Intruder 150 FI', 'Kinetic Green Zing Electric',
       'Yamaha FZS 25 BS6', 'UM Renegade Commando Mojave',
       'Bajaj Pulsar AS 200', 'BMW G 310 R', 'KTM Duke 200',
       'Royal Enfield Bullet Electra', 'TVS Jupiter Classic 110',
       'Honda CB Unicorn 160', 'Royal Enfield Himalayan 2021',
       'Ola S1 Pro', 'Hero Xtreme 125R Dual Channel ABS', 'TVS Radeon',
       'Ather 450S', 'Bajaj Avenger Cruise 220', 'Hero Splendor Plus',
       'KTM Duke 200 ABS', 'Bajaj Pulsar N160 Dual Channel ABS',
       'Yamaha FZ-S FI Ver 4.0', 'Hero Passion Plus', 'Yamaha R15 V4',
       'Honda CB Hornet 160R', 'Hero Passion X Pro', 'Honda CB Unicorn',
       'Royal Enfield Thunderbird 500', 'Yamaha FZ-S FI V3',
       'Royal Enfield Classic 350', 'KTM Duke 250 2025',
       'TVS Apache RR 310', 'Ola S1', 'Honda Activa 6G',
       'Honda Livo Disc', 'Honda Hornet 2.0 Repsol Edition',
       'TVS Apache RTR 160 4V', 'Suzuki Intruder 150', 'BMW G 310 GS',
       'Bajaj Dominar 250 2022', 'Bajaj Chetak 3503', 'Ola S1 Air 3kWh',
       'Yamaha Fascino S', 'TVS iQube ST', 'KTM 390 Adventure 2022',
       'Hero Splendor Plus Xtec', 'Bajaj Avenger Street 150',
       'Honda Shine 125 Disc', 'River Indie',
       'Royal Enfield Thunderbird X 350', 'Jawa forty two',
       'Bajaj Pulsar NS400Z 2025', 'TVS Jupiter 125', 'Ola S1X 3 kWh',
       'Yamaha Aerox 155', 'Bajaj Pulsar 200 NS ABS',
       'Royal Enfield Meteor 350', 'Benelli 302R', 'Suzuki Gixxer SF',
       'Suzuki Access 125', 'Jawa 42 FJ', 'Bajaj Dominar 400 ABS BS6',
       'Oben EV Rorr EZ', 'Bajaj Pulsar NS200', 'Yamaha MT-15',
       'BMW G 310 RR', 'Bajaj Avenger Street 180',
       'Royal Enfield Bullet Standard 350', 'Harley Davidson X440 Denim',
       'Ather 450S 2025', 'Bajaj Pulsar RS 200 BS6', 'Vida V1 Plus',
       'Yamaha FZ1', 'Honda Dream Yuga', 'Hero Passion Pro BS6',
       'Hero XPulse 200', 'Bajaj Avenger 200 DTS-i',
       'Bajaj Pulsar RS 200 ABS', 'Ola S1 3kWh', 'KTM RC 200 GP',
       'Royal Enfield Himalayan', 'Suzuki GS 150R', 'Vida V1 Pro',
       'Royal Enfield Classic 350 BS VI', 'Hero Achiever',
       'TVS Radeon BS6', 'Harley Davidson X440 S', 'Revolt RV 400',
       'Yamaha FZ16', 'Royal Enfield Classic Stealth Black',
       'Royal Enfield Meteor 350 Supernova', 'Honda Shine 125',
       'TVS Jupiter ZX BS6', 'KTM 390 Adventure 2023',
       'Hero Glamour 125 Drum', 'Bajaj Pulsar RS 200',
       'Yamaha YZF R15 V3', 'Honda Livo Drum',
       'Hero Electric Optima CX2.0', 'Aprilia RS 457',
       'Honda CB350C DLX Pro Special Edition',
       'Royal Enfield Himalayan BS VI',
       'Bajaj Chetak Premium 2023 Edition', 'Yamaha MT-15 Ver 2.0',
       'Yamaha YZF R15 S V3.0', 'Jawa 350 Legacy Edition',
       'KTM Duke 250 2020', 'Honda CB350 DLX Pro',
       'Royal Enfield Hunter 350 2025', 'Bajaj Pulsar NS 125',
       'Hero HF Deluxe', 'Royal Enfield Interceptor 650 Twin',
       'Triumph Speed 400 2025', 'Ola S1 Pro Gen 3', 'Aprilia SR 160',
       'Hero Xtreme 125R', 'TVS Apache RTR 160',
       'Royal Enfield Classic 350 Dual Channel BS6',
       'Royal Enfield Scram 411', 'Yamaha SS125',
       'Royal Enfield Hunter 350 Retro', 'Yezdi Roadster Red',
       'Bajaj Pulsar N250 Dual Channel ABS',
       'Hero Xtreme 125R Single Seat', 'Suzuki Gixxer SF BS6',
       'Ola S1 Pro Gen2', 'Royal Enfield Thunderbird TwinSpark 350',
       'Hero Glamour 125', 'Jawa forty two BS6', 'Ampere Magnus',
       'Revolt RV400 BRZ', 'Honda Activa 6G Std', 'UM Renegade Commando',
       'Hero Glamour Xtec', 'Royal Enfield Bear 650', 'Vespa ZX 125 BS6',
       'KTM Duke 250', 'Honda Activa 5G Limited Edition',
       'Yezdi Roadster Dark', 'Yamaha RX 135',
       'Hero Xtreme 160R 4V Standard', 'Honda Activa 125 BS6',
       'Honda Unicorn Dazzler', 'Ola S1 Air', 'Jawa Jawa BS6',
       'TVS Apache RTR 200 4V ABS Race Edition 2.0', 'Benelli TNT 600 i',
       'Bicycle  Urban Terrain Blitz Kids Cycle 16T',
       'Hero Pleasure Plus XTec', 'Yezdi Adventure Matte',
       'TVS NTORQ 125 Race Edition', 'Triumph Tiger 900 Rally',
       'TVS Scooty Pep Plus BS6', 'TVS Apache RTR 160 4V Special Edition',
       'KTM 250 Adventure 2022',
       'Revolt RV400 Stealth Black Limited Edition', 'Hero Destini Prime',
       'Honda Shine BS6', 'Royal Enfield 2022 Meteor 350',
       'Yamaha Saluto 125', 'TVS iQube Electric',
       'Suzuki Gixxer Gixxer SF 150', 'TVS Apache RTR 310',
       'Bajaj Discover 100 DTS-Si', 'Bajaj Discover 100', 'TVS Raider SX',
       'Royal Enfield Bullet 350', 'Bajaj Platina 100',
       'Bajaj Chetak 3501 Standard', 'Yezdi Scrambler Single Tone',
       'Kawasaki Z650 ABS', 'Bicycle Trek', 'Honda XBlade',
       'Bajaj Pulsar 150 Twin Disc', 'Hero Glamour 125 Disc',
       'Bajaj Chetak Urbane', 'Royal Enfield Bullet 350 ES BS6',
       'Bajaj Discover 125', 'Suzuki Gixxer SF 250', 'Aprilia SXR 160',
       'Hero CD 100SS', 'Jawa Jawa', 'TVS Apache RTR 200 4V 2022',
       'TVS Apache RR 310 2025', 'Royal Enfield Himalayan 450',
       'Bajaj Pulsar 150', 'Hero Pleasure Plus BS6', 'rilox nova',
       'Honda CB125 Hornet', 'Hero CBZ Xtreme', 'Honda 2022 CB300R',
       'Honda Hness Anniversary Edition', 'Honda Livo 110',
       'Honda Aviator', 'TVS iQube S', 'Bicycle  Avon Charge',
       'Bajaj V12', 'Vespa VXL 125',
       'Hero Splendor Plus i3s Black and Accent', 'Hero HF Deluxe BS6',
       'Hero Xpulse 200 4V', 'Honda CB200X',
       'Bajaj Avenger Cruise 220 BS6', 'Honda Activa 5G',
       'Honda CBR 150R', 'Hero Pleasure', 'Tork Kratos R', 'Honda Dio',
       'Royal Enfield Classic Gunmetal Grey', 'Honda CBF Stunner',
       'Hero Karizma XMR', 'Brixton Crossfire 500 X', 'Aprilia SR 125',
       'Yezdi Adventure Matte 2024', 'Ola S1 X Gen 3 4kWh',
       'Bajaj Pulsar 125 Split Seat',
       'Jawa 42 Dual Channel ABS AllStar Black',
       'Royal Enfield Classic 350 Redditch Green', 'Hero Passion Pro i3s',
       'Yamaha FZ', 'Vespa SXL 125', 'Ola S1X', 'Honda CB300R',
       'Honda Dream Neo', 'Yamaha FZ FI V2', 'Harley Davidson Street 750',
       'Yamaha Fascino', 'Bajaj Avenger Street 220',
       'Royal Enfield Classic Chrome', 'Yamaha Cygnus Ray ZR',
       'Harley Davidson Street Rod', 'Yamaha MT-15 BS6',
       'KTM 390 Adventure X 2025', 'Yamaha SZ-RR',
       'TVS Raider Black Panther Edition', 'Honda Unicorn',
       'Hero XPulse 200T BS6', 'Honda Grazia 125 BS6',
       'Hero Electric Photon LP', 'Royal Enfield Bullet 500',
       'Yamaha FZ 25 BS6', 'Mahindra Centuro O1', 'Jawa 42 Dual Tone',
       'Yamaha Ray Z', 'KTM Duke 390', 'TVS Jupiter BS6', 'Honda SP125',
       'Honda Shine 125 Drum', 'Hero CD 100',
       'TVS NTORQ 125 Super Soldier Edition', 'BGauss B8 Lithium Ion',
       'Honda Shine 100', 'Hero Glamour PGM Fi',
       'Jawa 42 Dual Channel ABS Orion Red', 'Kinetic Luna Super',
       'TVS Jupiter ZX Disc BS6', 'TVS Apache RTR 200 4V 2020',
       'Honda Shine Celebration Edition', 'Yezdi Scrambler Dual Tone',
       'Hero CD Deluxe', 'Jawa Perak BS6',
       'Jawa 42 Bobber Dual Channel ABS', 'Bajaj Avenger Street 160 BS6',
       'Bajaj Pulsar 200 NS', 'KTM RC 390 2024', 'Honda Hness CB 350',
       'Royal Enfield Bullet Machismo A500', 'Okinawa Ridge Plus',
       'Ultraviolette F77 Mach 2', 'TVS Scooty Pep Plus',
       'Hero XPulse 200T', 'Ampere Magnus Pro', 'Hero Destini 125 VX',
       'Bajaj Pulsar 125 Carbon Fibre Disc Split Seat', 'Yamaha Alpha',
       'Harley Davidson Iron 883', 'Bicycle  United Clovis 5.2',
       'Joy e-bike  Wolf', 'Bajaj Pulsar 220 DTSFi',
       'Jawa 42 Dual Channel ABS Cosmic Carbon',
       'Kawasaki Ninja 300 BS6 2022', 'KTM RC 125 2020', 'Hero Karizma R',
       'Royal Enfield Classic 350 2021', 'KTM RC 200',
       'Bajaj CT110 ES BS6', 'Royal Enfield Super Meteor 650',
       'Honda Shine', 'Honda Dio BS6', 'Honda Unicorn 160 BS6',
       'Hero Passion XTec', 'TVS NTORQ Super Squad Edition',
       'Bajaj Pulsar 150 Neon', 'TVS Scooty Streak',
       'Suzuki Access 125 Special Edition', 'KTM Duke 200 2022',
       'Hero Maestro Edge 125 BS6', 'Hero Xtreme 160R 4V Connected 2.0',
       'Yamaha Fascino 125 Fi', 'TVS Jupiter 125 SmartXonnect',
       'TVS Apache RTR 200 4V', 'Ola S1 Pro Gen 3 3kWh',
       'BMW F 900 XR Pro', 'Yamaha FZ-S FI V3 BS6', 'Jawa Perak',
       'Honda CB350RS New Hue Edition', 'Bajaj Pulsar 220F BS6',
       'Honda Shine 125 Disc OBD2', 'Suzuki SlingShot Plus',
       'TVS Ronin TD', 'Hero Xtreme 160R 4V Pro', 'Hero XPulse 200 BS6',
       'Bajaj Pulsar 150 Neon BS6', 'TVS Raider 125', 'Hero Destini 125',
       'TVS Apache RR 310 2020', 'TVS Apache RTR 180',
       'Hero Splendor Pro', 'Bajaj Avenger 180 DTS-i', 'Honda CB350 DLX',
       'KTM RC 200 2020', 'Hero Maestro Edge', 'Hero Ignitor',
       'Hero Maestro Edge 125', 'Ampere Magnus Ex', 'KTM RC 125 2022',
       'Hero CBZ', 'Honda  Hornet', 'Yamaha Fascino 125 Fi Hybrid',
       'Bajaj Dominar 400', 'Hero Xtreme 160R', 'TVS Raider iGO',
       'Yamaha YZF R15 V3 BS6', 'Honda SP 160 Double Disc',
       'Harley Davidson X440 Vivid', 'Suzuki V-Strom 250',
       'Husqvarna Vitpilen 250', 'TVS Apache RTR 200 4V ABS',
       'KTM 390 Adventure', 'Kawasaki Ninja 300R',
       'Husqvarna Svartpilen 250', 'Triumph Scrambler 400 X',
       'Royal Enfield Continental GT 650 Twin', 'Bajaj Discover 150 S',
       'Ather Rizta S', 'Yamaha Fazer 125', 'Hero Glamour',
       'Bajaj Discover 125M', 'KTM RC 125', 'Honda Activa i',
       'Ather 450X Gen 3', 'Triumph Street Twin', 'Ola S1X 4 kWh',
       'Yezdi Adventure Single Headlight', 'Bajaj Discover DTSi 150',
       'Hero Destini 125 BS6', 'TVS Star City', 'Honda Dio 125 Smart',
       'Hero Super Splendor IBS', 'Suzuki Burgman Street',
       'Hero Xpulse 200 4V Rally Edition', 'Bicycle Montra', 'KTM RC 390',
       'TVS XL100 Comfort i-TOUCHstart BS6', 'Odysse E2go Lite',
       'Royal Enfield Himalayan 452',
       'Hero Splendor Plus Black and Accent', 'Kawasaki W175 BS6 2023',
       'Mahindra Gusto 125', 'Husqvarna Vitpilen 250 2020',
       'Royal Enfield Guerrilla 450 Flash', 'Bicycle Firefox',
       'Hero Xtreme 160R Stealth Edition', 'BMW G 310 GS BS6',
       'Bajaj CT110X', 'Bajaj Pulsar 125',
       'TVS NTORQ 125 Race Edition BS6', 'Husqvarna Svartpilen 401 2024',
       'Bicycle Decathlon', 'Bicycle Schnell', 'BSA Gold Star 650',
       'Bajaj Pulsar 125 Carbon Fibre Disc Single Seat',
       'KTM Duke 250 2022', 'Triumph Tiger Sport 660', 'TVS Scooty Pep',
       'Suzuki Access 125 BS6', 'Honda NX200 2025',
       'Benelli Imperiale 400 BS6', 'Yamaha Aerox 155 Version S',
       'Suzuki Gixxer 150', 'Bajaj Pulsar NS400Z', 'TVS Sport',
       'Ola S1 Pro Plus Gen 3 4kWh', 'Hero Xtreme 160R BS6',
       'Hero Glamour X 125 Disc', 'Husqvarna Svartpilen 250 2022',
       'Bicycle Toronto', 'Royal Enfield Shotgun 650', 'Yamaha FZS 25',
       "Jawa forty two Jawa 42 dual channel ABS Haley's teal",
       'Yamaha MT-15 Version 2.0 DLX 2025', 'Hero HF Deluxe i3s',
       'Aprilia Storm 125', 'Honda CB Shine Limited Edition',
       'TVS Apache RTR 200 Fi 4V Race Edition 2.0', 'Yezdi Roadster 2025',
       'Bajaj CT 125X', 'TVS Sport BS6', 'Kawasaki Ninja 650R',
       'Royal Enfield Bullet 350 Twinspark',
       'Hero Splendor iSmart 110 FI BS-VI',
       'Husqvarna Svartpilen 250 2020', 'Honda 2023 Activa 125 H-Smart',
       'TVS Jupiter Drum Alloy 2024', 'Bajaj 2021 Dominar 400',
       'Yamaha MT', 'Hero  2014',
       'Yamaha FZ25 Monster Energy MotoGP Edition',
       'Bajaj Pulsar NS 160 BS6', 'Suzuki Avenis 125 Standard Edition',
       'Yamaha Fazer FI V2', 'Ola Roadster X 4.5',
       'Yamaha RayZR Street Rally 125 Fi Hybrid', 'Keeway Vieste 300',
       'Yamaha Fazer', 'Aprilia RS 125', 'Suzuki V-Strom SX',
       'KTM RC 200 2022', 'Hero Super Splendor XTEC', 'Bicycle  Ladybird',
       'Yezdi Roadster Chrome', 'Bajaj Pulsar 125 Neon Disc Single Seat',
       'TVS iQube 09', 'Bajaj Pulsar 125 Neon', 'Bajaj Discover 150 F',
       'Hero Xtreme Sports', 'Ducati Diavel 1260',
       'Bajaj Pulsar 200 NS ABS NS 200', 'Hero Xpulse 200 4V Pro',
       'Suzuki Avenis 125 Ride Connect Edition',
       'Royal Enfield Thunderbird X 500', 'Yamaha Gladiator',
       'Aprilia SR 150', 'Bajaj Pulsar N150',
       'BMW G 310 RR Limited Edition', 'Bajaj Pulsar NS 200 BS6',
       'Yezdi Adventure Twin Headlight', 'Hero Super Splendor BS6',
       'Bajaj Avenger Street 220 BS6',
       'Royal Enfield Meteor 350 Fireball', 'Ola S1 Pro Gen 3 4kWh',
       'Royal Enfield 2023 Continental GT 650', 'TVS Ronin DS',
       'Keeway SR 250', 'Hero Splendor iSmart',
       'Royal Enfield Bullet Thunderbird X 350', 'TVS Ronin 2025',
       'TVS Star City Plus', 'Bajaj Pulsar 150 Twin Disc BS6',
       'Ather 450 Plus', 'Royal Enfield Bullet Trials Works Replica 350',
       'Hero XPulse 210', 'Honda Activa e', 'KTM Duke 125',
       'TVS Ronin TD Special Edition', 'Yamaha SZ-RR V2', 'Hero Maestro',
       'Yamaha SZ-R'], dtype=object)

In [127]:
df=df.drop('bike_name', axis = 1)

In [128]:
df

,brand_origin,Company,model_name,model_year,price(RS),city,state,finance(YES/NO)
0,UK / India,Royal Enfield,Classic 500,2016,100000,Mumbai,Maharashtra,Yes
1,Japan,Honda,Activa 125,2022,72000,Bangalore,Karnataka,Yes
2,India,Bajaj,Pulsar 220F,2015,40000,Pune,Maharashtra,Yes
3,Hungary,Keeway,SR 125,2024,110000,Pune,Maharashtra,Yes
4,India,Bajaj,Pulsar NS 160,2022,122000,Bangalore,Karnataka,Yes
...,...,...,...,...,...,...,...,...
1490,India,TVS,Jupiter 125,2022,70000,Nagpur,Maharashtra,Yes
1491,Austria,KTM,Duke 125,2020,65000,Gurugram,Haryana,Yes
1492,Japan,Yamaha,SZ-R,2012,25000,Chennai,Tamil Nadu,Yes
1493,Japan,Yamaha,SZ-RR,2019,55000,Nadia,West Bengal,Yes
1494,Japan,Honda,Shine 125 Disc,2022,70000,Thane,Maharashtra,Yes

In [129]:
df.to_csv("bike4sales_data.csv",index=False)